In [1]:
from brfss import bfs_data
import brfss

from acemodel import simulate_stack, simulate_trans
from acemodel import HouseModel
from spew import *

In [2]:
import pandas as pd

In [3]:
from modelmtds import bootstrap_mtd_fill

In [4]:
spdata = pd.read_csv('spew_data/2010_ver1_45079_synth_people.txt', low_memory = False)

In [5]:
spdata['relate'].unique()

array([ 0,  1,  2, 12,  3, 10,  9,  7,  5,  6,  8,  4, 11])

In [6]:
scbrfss = bfs_data('brfss/SCBRFSS.csv')

In [7]:
data_prex = './spew_data/2010_ver1_45079_synth_'
cdl_data = cdn_data(data_prex, age = 0)
len(cdl_data)

352058

In [8]:
display(cdl_data)

,sp_id_x,sp_hh_id,age,sex,race,sporder,relate,sp_id_y,hh_income,_RACE_G1,_INCOMG
0,164099532,48930706,49,2,2,1,0,48930706,115000,2,5
1,164099533,48930706,57,1,2,2,1,48930706,115000,2,5
2,164099534,48954569,49,2,2,1,0,48954569,115000,2,5
3,164099535,48954569,57,1,2,2,1,48954569,115000,2,5
4,164099538,48964134,49,2,2,1,0,48964134,115000,2,5
...,...,...,...,...,...,...,...,...,...,...,...
352053,164066165,48841329,50,1,1,1,0,48841329,90000,1,5
352054,164066169,48822193,50,1,1,1,0,48822193,90000,1,5
352055,164066170,48815049,50,1,1,1,0,48815049,90000,1,5
352056,164066171,48811092,50,1,1,1,0,48811092,90000,1,5
352057,164066175,48812365,50,1,1,1,0,48812365,90000,1,5

In [9]:
test_model = HouseModel(cdl_data, 1,1, step_method = bootstrap_mtd_fill)

In [10]:
test_model.step()

In [11]:
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
test_model.step()
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
bst_result = simulate_stack(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel); bst_result

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bst_result_bf = bfs_data(bst_result)

In [17]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [18]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [19]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
trans_rate = {ace:0.2 for ace in brfss.ace_list.values()}

In [21]:
bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel,
                           trans_rate = trans_rate); bst_result

36.2 s Â± 71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [22]:
bst_result_bf = bfs_data(bst_result)

In [23]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [24]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [25]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
rate_list = []
for i in range(50):
    print('*' * 40, 'transmit rates:'.upper(), '*' * 40)
    al = list(brfss.ace_list.values())
    rl = np.random.choice(4,12)/10 + 0.2
    if list(rl) in rate_list:
        continue
    rate_list.append(list(rl))
    trans_rate = dict(zip(al, rl))
    
    print(''.join(['{:>15}'.format(t) for t in al[0:6]]))    
    print(''.join(['{:>15.2}'.format(r) for r in rl[0:6]]))
    print(''.join(['{:>15}'.format(t) for t in al[6:]]))       
    print(''.join(['{:>15.2}'.format(r) for r in rl[6:]]))
    
    bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, 
                                step_num = 2, model = HouseModel, trans_rate = trans_rate)
    bst_result_bf = bfs_data(bst_result)
    print('\n\t simulation result:'.upper())
    display(bst_result)
    print('\n\t propotion:'.upper())
    display(bst_result_bf.get_prop_mat(1,1)['pr'])
    print('\n\t correlation:'.upper())
    display(bst_result_bf.get_corr_mat(1,1))
    
    print('\n\t children result:'.upper())
    display(bst_result[bst_result.age < 18])
    chd_simu_result = bfs_data(bst_result[bst_result.age < 18])
    print('\n\t propotion of children:'.upper())
    display(chd_simu_result.get_prop_mat(1,1)['pr'])
    print('\n\t correlation of children:'.upper())
    display(chd_simu_result.get_corr_mat(1,1))
    
    print('')
    
for r in rate_list:
    print(''.join(['{:>5.2}'.format(x) for x in r]))

**************************************** TRANSMIT RATES: ****************************************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.4            0.2            0.3            0.5            0.2            0.4
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.3            0.4            0.5            0.4            0.5            0.2

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
352057,163646287,60,5,5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190480,0.117369,0.057788,0.042139,0.087538,0.095770,0.081995,0.126009,0.065042,0.059337,0.049393,0.046377
alcoabuse,0.117369,0.292607,0.061374,0.067650,0.135300,0.154047,0.113294,0.163991,0.088516,0.076453,0.060070,0.067976
drugabuse,0.057788,0.061374,0.096096,0.041568,0.052653,0.049148,0.037982,0.063819,0.036026,0.032195,0.028364,0.025919
prison,0.042139,0.067650,0.041568,0.097563,0.052001,0.056973,0.035537,0.057380,0.039368,0.031950,0.024370,0.030157
patdivorce,0.087538,0.135300,0.052653,0.052001,0.269052,0.118103,0.093732,0.137827,0.065368,0.050697,0.044584,0.060478
phyabuse1,0.095770,0.154047,0.049148,0.056973,0.118103,0.230011,0.113864,0.153476,0.071073,0.060559,0.050941,0.061619
phyabuse2,0.081995,0.113294,0.037982,0.035537,0.093732,0.113864,0.197164,0.165050,0.073030,0.059174,0.049067,0.055424
verbalabuse,0.126009,0.163991,0.063819,0.057380,0.137827,0.153476,0.165050,0.310294,0.103757,0.082729,0.064716,0.071481
sexabuse1,0.065042,0.088516,0.036026,0.039368,0.065368,0.071073,0.073030,0.103757,0.160893,0.105714,0.080121,0.036270
sexabuse2,0.059337,0.076453,0.032195,0.031950,0.050697,0.060559,0.059174,0.082729,0.105714,0.125194,0.072622,0.034396
sexabuse3,0.049393,0.060070,0.028364,0.024370,0.044584,0.050941,0.049067,0.064716,0.080121,0.072622,0.098541,0.027305
foodinsecure,0.046377,0.067976,0.025919,0.030157,0.060478,0.061619,0.055424,0.071481,0.036270,0.034396,0.027305,0.189094

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.344987,0.341165,0.202159,0.208387,0.314407,0.284449,0.368293,0.238385,0.273097,0.261651,0.067364
alcoabuse,0.344987,1.000000,0.248017,0.289655,0.280402,0.453054,0.307179,0.347774,0.247879,0.264475,0.230359,0.070982
drugabuse,0.341165,0.248017,1.000000,0.368124,0.205037,0.218052,0.162338,0.249382,0.189902,0.206740,0.215103,0.067134
prison,0.202159,0.289655,0.368124,1.000000,0.195699,0.276541,0.138081,0.197476,0.217108,0.200986,0.166858,0.100770
patdivorce,0.208387,0.280402,0.205037,0.195699,1.000000,0.301228,0.230592,0.264883,0.135502,0.115926,0.136724,0.055290
phyabuse1,0.314407,0.453054,0.218052,0.276541,0.301228,1.000000,0.409203,0.421731,0.220308,0.228067,0.225434,0.109986
phyabuse2,0.284449,0.307179,0.162338,0.138081,0.230592,0.409203,1.000000,0.564352,0.282567,0.261950,0.249943,0.116447
verbalabuse,0.368293,0.347774,0.249382,0.197476,0.264883,0.421731,0.564352,1.000000,0.316704,0.286629,0.247602,0.070692
sexabuse1,0.238385,0.247879,0.189902,0.217108,0.135502,0.220308,0.282567,0.316704,1.000000,0.703722,0.586844,0.040633
sexabuse2,0.273097,0.264475,0.206740,0.200986,0.115926,0.228067,0.261950,0.286629,0.703722,1.000000,0.611200,0.082740
sexabuse3,0.261651,0.230359,0.215103,0.166858,0.136724,0.225434,0.249943,0.247602,0.586844,0.611200,1.000000,0.074296
foodinsecure,0.067364,0.070982,0.067134,0.100770,0.055290,0.109986,0.116447,0.070692,0.040633,0.082740,0.074296,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.116838,0.020619,0.015808,0.016495,0.014433,0.031615,0.018557,0.035052,0.024742,0.017182,0.014433,0.010309
alcoabuse,0.020619,0.088660,0.006873,0.012371,0.005498,0.021306,0.008935,0.022680,0.011684,0.008247,0.013058,0.006873
drugabuse,0.015808,0.006873,0.052921,0.015120,0.006873,0.012371,0.009622,0.018557,0.008247,0.004811,0.006186,0.006873
prison,0.016495,0.012371,0.015120,0.074914,0.016495,0.022680,0.010997,0.023368,0.012371,0.013058,0.010997,0.013058
patdivorce,0.014433,0.005498,0.006873,0.016495,0.076289,0.018557,0.013058,0.017869,0.009622,0.008247,0.008247,0.009622
phyabuse1,0.031615,0.021306,0.012371,0.022680,0.018557,0.140893,0.023368,0.044674,0.024742,0.017869,0.019244,0.013058
phyabuse2,0.018557,0.008935,0.009622,0.010997,0.013058,0.023368,0.083162,0.037801,0.016495,0.013746,0.010309,0.010309
verbalabuse,0.035052,0.022680,0.018557,0.023368,0.017869,0.044674,0.037801,0.180069,0.040550,0.028866,0.027491,0.018557
sexabuse1,0.024742,0.011684,0.008247,0.012371,0.009622,0.024742,0.016495,0.040550,0.110653,0.032302,0.028179,0.010997
sexabuse2,0.017182,0.008247,0.004811,0.013058,0.008247,0.017869,0.013746,0.028866,0.032302,0.078351,0.027491,0.008935
sexabuse3,0.014433,0.013058,0.006186,0.010997,0.008247,0.019244,0.010309,0.027491,0.028179,0.027491,0.078351,0.006186
foodinsecure,0.010309,0.006873,0.006873,0.013058,0.009622,0.013058,0.010309,0.018557,0.010997,0.008935,0.006186,0.072852

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.112361,0.133829,0.091552,0.064728,0.135590,0.099665,0.113527,0.117235,0.092999,0.061151,0.021529
alcoabuse,0.112361,1.000000,0.034271,0.076564,-0.016770,0.089128,0.019896,0.061485,0.021009,0.017031,0.080014,0.005601
drugabuse,0.133829,0.034271,1.000000,0.189286,0.047713,0.063102,0.084458,0.104940,0.034053,0.011047,0.033896,0.051860
prison,0.091552,0.076564,0.189286,1.000000,0.154254,0.132391,0.065573,0.097654,0.049425,0.101621,0.072475,0.111093
patdivorce,0.064728,-0.016770,0.047713,0.154254,1.000000,0.084543,0.091598,0.040511,0.014175,0.031824,0.031824,0.058909
phyabuse1,0.135590,0.089128,0.063102,0.132391,0.084543,1.000000,0.121277,0.144394,0.083855,0.073058,0.087761,0.030900
phyabuse2,0.099665,0.019896,0.084458,0.065573,0.091598,0.121277,1.000000,0.215136,0.084192,0.097437,0.051125,0.059233
verbalabuse,0.113527,0.061485,0.104940,0.097654,0.040511,0.144394,0.215136,1.000000,0.171105,0.142923,0.129610,0.054458
sexabuse1,0.117235,0.021009,0.034053,0.049425,0.014175,0.083855,0.084192,0.171105,1.000000,0.280345,0.231427,0.036002
sexabuse2,0.092999,0.017031,0.011047,0.101621,0.031824,0.073058,0.097437,0.142923,0.280345,1.000000,0.295694,0.046202
sexabuse3,0.061151,0.080014,0.033896,0.072475,0.031824,0.087761,0.051125,0.129610,0.231427,0.295694,1.000000,0.006838
foodinsecure,0.021529,0.005601,0.051860,0.111093,0.058909,0.030900,0.059233,0.054458,0.036002,0.046202,0.006838,1.000000

**************************************** TRANSMIT RATES: ****************************************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.4            0.5            0.4            0.4            0.5            0.5
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.4            0.4            0.2            0.2            0.5            0.3

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,165121905,85,1,1,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,165641324,50,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
352054,163646283,60,5,5,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
352057,163646287,60,5,5,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190399,0.121200,0.058848,0.040998,0.088434,0.092102,0.082729,0.123563,0.061048,0.056565,0.048007,0.043769
alcoabuse,0.121200,0.313962,0.068221,0.079387,0.142636,0.159589,0.118592,0.174016,0.092184,0.078572,0.062271,0.068628
drugabuse,0.058848,0.068221,0.104409,0.046948,0.057951,0.052001,0.042791,0.068791,0.036107,0.033255,0.027957,0.020295
prison,0.040998,0.079387,0.046948,0.107262,0.058195,0.062271,0.042139,0.061863,0.043117,0.035211,0.028201,0.028201
patdivorce,0.088434,0.142636,0.057951,0.058195,0.280137,0.123237,0.094058,0.138805,0.063249,0.051593,0.044910,0.054528
phyabuse1,0.092102,0.159589,0.052001,0.062271,0.123237,0.235145,0.118755,0.155514,0.070340,0.059826,0.047763,0.054935
phyabuse2,0.082729,0.118592,0.042791,0.042139,0.094058,0.118755,0.197979,0.161464,0.069362,0.056076,0.045888,0.045970
verbalabuse,0.123563,0.174016,0.068791,0.061863,0.138805,0.155514,0.161464,0.308746,0.099927,0.079876,0.060559,0.065857
sexabuse1,0.061048,0.092184,0.036107,0.043117,0.063249,0.070340,0.069362,0.099927,0.155514,0.102861,0.076697,0.039204
sexabuse2,0.056565,0.078572,0.033255,0.035211,0.051593,0.059826,0.056076,0.079876,0.102861,0.120711,0.068302,0.028527
sexabuse3,0.048007,0.062271,0.027957,0.028201,0.044910,0.047763,0.045888,0.060559,0.076697,0.068302,0.096911,0.026490
foodinsecure,0.043769,0.068628,0.020295,0.028201,0.054528,0.054935,0.045970,0.065857,0.039204,0.028527,0.026490,0.182574

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.337088,0.324576,0.169351,0.199062,0.284261,0.287853,0.357146,0.220960,0.262544,0.254460,0.059384
alcoabuse,0.337088,1.000000,0.249722,0.318289,0.262382,0.435739,0.305158,0.359516,0.257796,0.269004,0.231936,0.063065
drugabuse,0.324576,0.249722,1.000000,0.377787,0.209015,0.211667,0.181533,0.258765,0.179306,0.207292,0.197186,0.010434
prison,0.169351,0.318289,0.377787,1.000000,0.202555,0.282311,0.169521,0.201085,0.235738,0.220831,0.194507,0.072089
patdivorce,0.199062,0.262382,0.209015,0.202555,1.000000,0.301214,0.215696,0.252167,0.120952,0.121516,0.133697,0.019495
phyabuse1,0.284261,0.435739,0.211667,0.282311,0.301214,1.000000,0.427250,0.423204,0.219741,0.227562,0.199061,0.073268
phyabuse2,0.287853,0.305158,0.181533,0.169521,0.215696,0.427250,1.000000,0.545064,0.267119,0.247868,0.226509,0.063816
verbalabuse,0.357146,0.359516,0.258765,0.201085,0.252167,0.423204,0.545064,1.000000,0.310078,0.283090,0.224178,0.053164
sexabuse1,0.220960,0.257796,0.179306,0.235738,0.120952,0.219741,0.267119,0.310078,1.000000,0.712226,0.574823,0.077227
sexabuse2,0.262544,0.269004,0.207292,0.220831,0.121516,0.227562,0.247868,0.283090,0.712226,1.000000,0.587296,0.051554
sexabuse3,0.254460,0.231936,0.197186,0.194507,0.133697,0.199061,0.226509,0.224178,0.574823,0.587296,1.000000,0.076965
foodinsecure,0.059384,0.063065,0.010434,0.072089,0.019495,0.073268,0.063816,0.053164,0.077227,0.051554,0.076965,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.112715,0.043986,0.015808,0.013058,0.034364,0.034364,0.029553,0.030241,0.006873,0.009622,0.019931,0.018557
alcoabuse,0.043986,0.232302,0.026804,0.032990,0.068729,0.079725,0.046048,0.064605,0.017182,0.018557,0.039175,0.026804
drugabuse,0.015808,0.026804,0.060481,0.014433,0.024055,0.023368,0.015120,0.016495,0.002749,0.005498,0.005498,0.003436
prison,0.013058,0.032990,0.014433,0.073540,0.029553,0.026117,0.014433,0.021306,0.004124,0.006873,0.014433,0.010309
patdivorce,0.034364,0.068729,0.024055,0.029553,0.205498,0.057732,0.036426,0.054296,0.010997,0.010309,0.028866,0.017869
phyabuse1,0.034364,0.079725,0.023368,0.026117,0.057732,0.186942,0.043986,0.061168,0.013058,0.012371,0.026117,0.024742
phyabuse2,0.029553,0.046048,0.015120,0.014433,0.036426,0.043986,0.120962,0.041237,0.010309,0.009622,0.015808,0.015120
verbalabuse,0.030241,0.064605,0.016495,0.021306,0.054296,0.061168,0.041237,0.168385,0.015808,0.009622,0.021993,0.017869
sexabuse1,0.006873,0.017182,0.002749,0.004124,0.010997,0.013058,0.010309,0.015808,0.044674,0.007560,0.015120,0.002062
sexabuse2,0.009622,0.018557,0.005498,0.006873,0.010309,0.012371,0.009622,0.009622,0.007560,0.037801,0.013746,0.004124
sexabuse3,0.019931,0.039175,0.005498,0.014433,0.028866,0.026117,0.015808,0.021993,0.015120,0.013746,0.081100,0.010997
foodinsecure,0.018557,0.026804,0.003436,0.010309,0.017869,0.024742,0.015120,0.017869,0.002062,0.004124,0.010997,0.086598

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.133301,0.119260,0.057779,0.087661,0.107818,0.154371,0.095158,0.028126,0.088893,0.124986,0.098894
alcoabuse,0.133301,1.000000,0.126698,0.144302,0.123014,0.220469,0.130339,0.161291,0.077995,0.121377,0.176397,0.056304
drugabuse,0.119260,0.126698,1.000000,0.160480,0.120705,0.129783,0.100403,0.070747,0.000959,0.070654,0.009117,-0.026865
prison,0.057779,0.144302,0.160480,1.000000,0.136922,0.121550,0.065059,0.091352,0.015549,0.082222,0.118854,0.053683
patdivorce,0.087661,0.123014,0.120705,0.136922,1.000000,0.122616,0.087801,0.130239,0.021758,0.032978,0.110604,0.000648
phyabuse1,0.107818,0.220469,0.129783,0.121550,0.122616,1.000000,0.168124,0.203511,0.058444,0.071344,0.102942,0.078009
phyabuse2,0.154371,0.130339,0.100403,0.065059,0.087801,0.168124,1.000000,0.171025,0.072820,0.081197,0.067376,0.050651
verbalabuse,0.095158,0.161291,0.070747,0.091352,0.130239,0.203511,0.171025,1.000000,0.107174,0.045637,0.081614,0.031238
sexabuse1,0.028126,0.077995,0.000959,0.015549,0.021758,0.058444,0.072820,0.107174,1.000000,0.149026,0.203868,-0.031097
sexabuse2,0.088893,0.121377,0.070654,0.082222,0.032978,0.071344,0.081197,0.045637,0.149026,1.000000,0.205139,0.015852
sexabuse3,0.124986,0.176397,0.009117,0.118854,0.110604,0.102942,0.067376,0.081614,0.203868,0.205139,1.000000,0.051754
foodinsecure,0.098894,0.056304,-0.026865,0.053683,0.000648,0.078009,0.050651,0.031238,-0.031097,0.015852,0.051754,1.000000

  0.4  0.2  0.3  0.5  0.2  0.4  0.3  0.4  0.5  0.4  0.5  0.2
  0.4  0.5  0.4  0.4  0.5  0.5  0.4  0.4  0.2  0.2  0.5  0.3