In [1]:
from brfss import bfs_data
import brfss

from acemodel import simulate_stack, simulate_trans
from acemodel import HouseModel
from spew import *

In [2]:
import pandas as pd

In [3]:
from modelmtds import bootstrap_mtd_fill

In [4]:
spdata = pd.read_csv('spew_data/2010_ver1_45079_synth_people.txt', low_memory = False)

In [5]:
spdata['relate'].unique()

array([ 0,  1,  2, 12,  3, 10,  9,  7,  5,  6,  8,  4, 11])

In [6]:
scbrfss = bfs_data('brfss/SCBRFSS.csv')

In [7]:
data_prex = './spew_data/2010_ver1_45079_synth_'
cdl_data = cdn_data(data_prex, age = 0)
len(cdl_data)

352058

In [8]:
display(cdl_data)

,sp_id_x,sp_hh_id,age,sex,race,sporder,relate,sp_id_y,hh_income,_RACE_G1,_INCOMG
0,164099532,48930706,49,2,2,1,0,48930706,115000,2,5
1,164099533,48930706,57,1,2,2,1,48930706,115000,2,5
2,164099534,48954569,49,2,2,1,0,48954569,115000,2,5
3,164099535,48954569,57,1,2,2,1,48954569,115000,2,5
4,164099538,48964134,49,2,2,1,0,48964134,115000,2,5
...,...,...,...,...,...,...,...,...,...,...,...
352053,164066165,48841329,50,1,1,1,0,48841329,90000,1,5
352054,164066169,48822193,50,1,1,1,0,48822193,90000,1,5
352055,164066170,48815049,50,1,1,1,0,48815049,90000,1,5
352056,164066171,48811092,50,1,1,1,0,48811092,90000,1,5
352057,164066175,48812365,50,1,1,1,0,48812365,90000,1,5

In [9]:
test_model = HouseModel(cdl_data, 1,1, step_method = bootstrap_mtd_fill)

In [10]:
test_model.step()

In [11]:
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
test_model.step()
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
bst_result = simulate_stack(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel); bst_result

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bst_result_bf = bfs_data(bst_result)

In [17]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [18]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [19]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
trans_rate = {ace:0.2 for ace in brfss.ace_list.values()}

In [21]:
%%timeit
bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel,
                           trans_rate = trans_rate); bst_result

36.2 s Â± 71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [22]:
bst_result_bf = bfs_data(bst_result)

In [23]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [24]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [25]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
for i in range(2):
    print('transmit rates:')
    al = list(brfss.ace_list.values())
    rl = np.random.choice(4,12)/10 + 0.2
    trans_rate = dict(zip(al, rl))
    
    for t in list(brfss.ace_list.values())[0:6]:
        print('{:>15}'.format(t), end='')
    print('')    
    print(''.join(['{:>15.2}'.format(r) for r in rl[0:6]]))
    for t in list(brfss.ace_list.values())[6:]:
        print('{:>15}'.format(t), end='')
    print('')    
    print(''.join(['{:>15.2}'.format(r) for r in rl[6:]]))
    
    bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, 
                                step_num = 2, model = HouseModel, trans_rate = trans_rate)
    bst_result_bf = bfs_data(bst_result)
    display(bst_result_bf)
    print('\n\t propotion:')
    print(bst_result_bf.get_prop_mat(1,1)['pr'])
    print('\n\t correlation:')
    print(bst_result_bf.get_corr_mat(1,1))
    
    chd_simu_result = bfs_data(bst_result[bst_result.age < 18])
    print('\n\t propotion of children:')
    print(chd_simu_result.get_prop_mat(1,1)['pr'])
    print('\n\t correlation of children:')
    print(chd_simu_result.get_corr_mat(1,1))
    
    print('')

transmit rates:
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.3            0.5            0.3            0.4            0.3            0.5
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.5            0.4            0.4            0.3            0.5            0.2

	 propotion:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       0.190806   0.118103   0.054120  0.043443    0.083625   0.091939
alcoabuse     0.118103   0.308338   0.059092  0.075230    0.133833   0.152009
drugabuse     0.054120   0.059092   0.095036  0.040427    0.049311   0.043117
prison        0.043443   0.075230   0.040427  0.103024    0.053550   0.058195
patdivorce    0.083625   0.133833   0.049311  0.053550    0.265792   0.112886
phyabuse1     0.091939   0.152009   0.043117  0.058195    0.112886   0.229196
phyabuse2     0.078491   0.114924   0.034803  0.037330    0.090472   0.110930
verbalabuse   0.124460   0.168147   0.063412  0.059581    0.133181   0.150053
sexabuse1     0.064634   0.090227   0.033499  0.041568    0.061782   0.070095
sexabuse2     0.055669   0.075067   0.028772  0.031054    0.047763   0.057625
sexabuse3     0.045562   0.055424   0.025430  0.025348    0.039857   0.044828
foodinsecure  0.044258   0.073845   0.022740  0.032276    0.060885   0.061293

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.078491     0.124460   0.064634   0.055669   0.045562
alcoabuse      0.114924     0.168147   0.090227   0.075067   0.055424
drugabuse      0.034803     0.063412   0.033499   0.028772   0.025430
prison         0.037330     0.059581   0.041568   0.031054   0.025348
patdivorce     0.090472     0.133181   0.061782   0.047763   0.039857
phyabuse1      0.110930     0.150053   0.070095   0.057625   0.044828
phyabuse2      0.201646     0.163665   0.074089   0.055913   0.047029
verbalabuse    0.163665     0.313391   0.105551   0.080365   0.059581
sexabuse1      0.074089     0.105551   0.160567   0.101231   0.075556
sexabuse2      0.055913     0.080365   0.101231   0.121444   0.065939
sexabuse3      0.047029     0.059581   0.075556   0.065939   0.094466
foodinsecure   0.056973     0.074497   0.045643   0.033662   0.027305

              foodinsecure
depress           0.044258
alcoabuse         0.073845
drugabuse         0.022740
prison            0.032276
patdivorce        0.060885
phyabuse1         0.061293
phyabuse2         0.056973
verbalabuse       0.074497
sexabuse1         0.045643
sexabuse2         0.033662
sexabuse3         0.027305
foodinsecure      0.184041

	 correlation:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       1.000000   0.326626   0.312290  0.199125    0.189598   0.291886
alcoabuse     0.326626   1.000000   0.219954  0.309607    0.254305   0.419050
drugabuse     0.312290   0.219954   1.000000  0.343648    0.185652   0.173083
prison        0.199125   0.309607   0.343648  1.000000    0.194854   0.270661
patdivorce    0.189598   0.254305   0.185652  0.194854    1.000000   0.279885
phyabuse1     0.291886   0.419050   0.173083  0.270661    0.279885   1.000000
phyabuse2     0.253810   0.284680   0.132913  0.135734    0.208051   0.383731
verbalabuse   0.354761   0.333849   0.247199  0.193559    0.243436   0.401211
sexabuse1     0.235667   0.240164   0.169406  0.224238    0.117795   0.215760
sexabuse2     0.253186   0.249402   0.179868  0.186736    0.107306   0.216984
sexabuse3     0.239613   0.194695   0.191812  0.175641    0.114149   0.188538
foodinsecure  0.060036   0.095541   0.046193  0.113036    0.069915   0.117334

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.253810     0.354761   0.235667   0.253186   0.239613
alcoabuse      0.284680     0.333849   0.240164   0.249402   0.194695
drugabuse      0.132913     0.247199   0.169406   0.179868   0.191812
prison         0.135734     0.193559   0.224238   0.186736   0.175641
patdivorce     0.208051     0.243436   0.117795   0.107306   0.114149
phyabuse1      0.383731     0.401211   0.215760   0.216984   0.188538
phyabuse2      1.000000     0.539817   0.283165   0.239774   0.238436
verbalabuse    0.539817     1.000000   0.324307   0.279207   0.220948
sexabuse1      0.283165     0.324307   1.000000   0.681539   0.562394
sexabuse2      0.239774     0.279207   0.681539   1.000000   0.570118
sexabuse3      0.238436     0.220948   0.562394   0.570118   1.000000
foodinsecure   0.127741     0.093569   0.113113   0.089361   0.087516

              foodinsecure
depress           0.060036
alcoabuse         0.095541
drugabuse         0.046193
prison            0.113036
patdivorce        0.069915
phyabuse1         0.117334
phyabuse2         0.127741
verbalabuse       0.093569
sexabuse1         0.113113
sexabuse2         0.089361
sexabuse3         0.087516
foodinsecure      1.000000

	 propotion of children:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       0.082474   0.030241   0.008247  0.011684    0.013746   0.026117
alcoabuse     0.030241   0.233677   0.014433  0.030928    0.047423   0.075601
drugabuse     0.008247   0.014433   0.041237  0.009622    0.009622   0.010997
prison        0.011684   0.030928   0.009622  0.068729    0.019931   0.022680
patdivorce    0.013746   0.047423   0.009622  0.019931    0.131271   0.036426
phyabuse1     0.026117   0.075601   0.010997  0.022680    0.036426   0.169072
phyabuse2     0.017869   0.059794   0.007560  0.018557    0.029553   0.052234
verbalabuse   0.026804   0.064605   0.014433  0.017869    0.035739   0.048110
sexabuse1     0.013746   0.036426   0.013746  0.011684    0.017869   0.030241
sexabuse2     0.006186   0.023368   0.005498  0.006186    0.013058   0.017869
sexabuse3     0.008935   0.028866   0.009622  0.012371    0.015808   0.021993
foodinsecure  0.005498   0.021993   0.000687  0.007560    0.011684   0.018557

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.017869     0.026804   0.013746   0.006186   0.008935
alcoabuse      0.059794     0.064605   0.036426   0.023368   0.028866
drugabuse      0.007560     0.014433   0.013746   0.005498   0.009622
prison         0.018557     0.017869   0.011684   0.006186   0.012371
patdivorce     0.029553     0.035739   0.017869   0.013058   0.015808
phyabuse1      0.052234     0.048110   0.030241   0.017869   0.021993
phyabuse2      0.148454     0.061168   0.024742   0.013058   0.019244
verbalabuse    0.061168     0.178694   0.032990   0.019244   0.024055
sexabuse1      0.024742     0.032990   0.093471   0.021993   0.028866
sexabuse2      0.013058     0.019244   0.021993   0.056357   0.016495
sexabuse3      0.019244     0.024055   0.028866   0.016495   0.070103
foodinsecure   0.014433     0.017869   0.006873   0.004124   0.004124

              foodinsecure
depress           0.005498
alcoabuse         0.021993
drugabuse         0.000687
prison            0.007560
patdivorce        0.011684
phyabuse1         0.018557
phyabuse2         0.014433
verbalabuse       0.017869
sexabuse1         0.006873
sexabuse2         0.004124
sexabuse3         0.004124
foodinsecure      0.067354

	 correlation of children:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       1.000000   0.094222   0.088604  0.086437    0.031424   0.118060
alcoabuse     0.094222   1.000000   0.057009  0.138873    0.117195   0.227558
drugabuse     0.088604   0.057009   1.000000  0.134935    0.062679   0.054000
prison        0.086437   0.138873   0.134935  1.000000    0.127690   0.116639
patdivorce    0.031424   0.117195   0.062679  0.127690    1.000000   0.112438
phyabuse1     0.118060   0.227558   0.054000  0.116639    0.112438   1.000000
phyabuse2     0.057520   0.166849   0.020345  0.092869    0.083832   0.203611
verbalabuse   0.114500   0.140938   0.092737  0.057656    0.094932   0.124645
sexabuse1     0.075389   0.118396   0.170892  0.071421    0.056962   0.132324
sexabuse2     0.024237   0.104504   0.069225  0.039632    0.072683   0.096498
sexabuse3     0.044892   0.115550   0.132588  0.116931    0.076606   0.105965
foodinsecure -0.000822   0.058967  -0.041942  0.046224    0.033580   0.076314

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.057520     0.114500   0.075389   0.024237   0.044892
alcoabuse      0.166849     0.140938   0.118396   0.104504   0.115550
drugabuse      0.020345     0.092737   0.170892   0.069225   0.132588
prison         0.092869     0.057656   0.071421   0.039632   0.116931
patdivorce     0.083832     0.094932   0.056962   0.072683   0.076606
phyabuse1      0.203611     0.124645   0.132324   0.096498   0.105965
phyabuse2      1.000000     0.254319   0.104990   0.057224   0.097345
verbalabuse    0.254319     1.000000   0.146051   0.103833   0.117858
sexabuse1      0.104990     0.146051   1.000000   0.249154   0.300228
sexabuse2      0.057224     0.103833   0.249154   1.000000   0.213045
sexabuse3      0.097345     0.117858   0.300228   0.213045   1.000000
foodinsecure   0.049758     0.060757   0.007912   0.005672  -0.009345

              foodinsecure
depress          -0.000822
alcoabuse         0.058967
drugabuse        -0.041942
prison            0.046224
patdivorce        0.033580
phyabuse1         0.076314
phyabuse2         0.049758
verbalabuse       0.060757
sexabuse1         0.007912
sexabuse2         0.005672
sexabuse3        -0.009345
foodinsecure      1.000000

transmit rates:
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.5            0.3            0.2            0.2            0.4            0.5
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.4            0.2            0.5            0.3            0.4            0.5

	 propotion:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       0.188931   0.110033   0.050534  0.041079    0.084277   0.093488
alcoabuse     0.110033   0.293178   0.059663  0.073600    0.135952   0.150787
drugabuse     0.050534   0.059663   0.089249  0.038308    0.050208   0.047029
prison        0.041079   0.073600   0.038308  0.097400    0.053631   0.057951
patdivorce    0.084277   0.135952   0.050208  0.053631    0.271986   0.116554
phyabuse1     0.093488   0.150787   0.047029  0.057951    0.116554   0.229522
phyabuse2     0.082240   0.110359   0.035944  0.038226    0.091613   0.119244
verbalabuse   0.120385   0.162768   0.060315  0.061537    0.135708   0.153069
sexabuse1     0.065450   0.094629   0.034559  0.043443    0.069199   0.075393
sexabuse2     0.057625   0.077431   0.029994  0.034314    0.053631   0.061456
sexabuse3     0.046785   0.056728   0.025511  0.026000    0.044665   0.048252
foodinsecure  0.041650   0.061782   0.020784  0.024615    0.054772   0.056647

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.082240     0.120385   0.065450   0.057625   0.046785
alcoabuse      0.110359     0.162768   0.094629   0.077431   0.056728
drugabuse      0.035944     0.060315   0.034559   0.029994   0.025511
prison         0.038226     0.061537   0.043443   0.034314   0.026000
patdivorce     0.091613     0.135708   0.069199   0.053631   0.044665
phyabuse1      0.119244     0.153069   0.075393   0.061456   0.048252
phyabuse2      0.205803     0.164643   0.076616   0.057299   0.045970
verbalabuse    0.164643     0.303366   0.106366   0.081180   0.058766
sexabuse1      0.076616     0.106366   0.167169   0.105958   0.078327
sexabuse2      0.057299     0.081180   0.105958   0.123726   0.067813
sexabuse3      0.045970     0.058766   0.078327   0.067813   0.093569
foodinsecure   0.047926     0.064716   0.039694   0.031787   0.021925

              foodinsecure
depress           0.041650
alcoabuse         0.061782
drugabuse         0.020784
prison            0.024615
patdivorce        0.054772
phyabuse1         0.056647
phyabuse2         0.047926
verbalabuse       0.064716
sexabuse1         0.039694
sexabuse2         0.031787
sexabuse3         0.021925
foodinsecure      0.197327

	 correlation:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       1.000000   0.306642   0.301706  0.195381    0.188820   0.304489
alcoabuse     0.306642   1.000000   0.258094  0.333730    0.277501   0.436167
drugabuse     0.301706   0.258094   1.000000  0.350335    0.204414   0.221401
prison        0.195381   0.333730   0.350335  1.000000    0.205700   0.285481
patdivorce    0.188820   0.277501   0.204414  0.205700    1.000000   0.289255
phyabuse1     0.304489   0.436167   0.221401  0.285481    0.289255   1.000000
phyabuse2     0.273961   0.271803   0.152489  0.151672    0.198094   0.423540
verbalabuse   0.350470   0.352787   0.253609  0.234689    0.260048   0.431613
sexabuse1     0.231860   0.268573   0.184611  0.245502    0.142928   0.235960
sexabuse2     0.265716   0.274582   0.201882  0.228039    0.136359   0.238743
sexabuse3     0.255314   0.220980   0.206677  0.195564    0.148280   0.218632
foodinsecure  0.028041   0.021692   0.027963  0.045722    0.006223   0.067854

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.273961     0.350470   0.231860   0.265716   0.255314
alcoabuse      0.271803     0.352787   0.268573   0.274582   0.220980
drugabuse      0.152489     0.253609   0.184611   0.201882   0.206677
prison         0.151672     0.234689   0.245502   0.228039   0.195564
patdivorce     0.198094     0.260048   0.142928   0.136359   0.148280
phyabuse1      0.423540     0.431613   0.235960   0.238743   0.218632
phyabuse2      1.000000     0.549936   0.279826   0.239151   0.226879
verbalabuse    0.549936     1.000000   0.324444   0.288340   0.226920
sexabuse1      0.279826     0.324444   1.000000   0.694086   0.576869
sexabuse2      0.239151     0.288340   0.694086   1.000000   0.586450
sexabuse3      0.226879     0.226920   0.576869   0.586450   1.000000
foodinsecure   0.045465     0.026529   0.045163   0.056263   0.029865

              foodinsecure
depress           0.028041
alcoabuse         0.021692
drugabuse         0.027963
prison            0.045722
patdivorce        0.006223
phyabuse1         0.067854
phyabuse2         0.045465
verbalabuse       0.026529
sexabuse1         0.045163
sexabuse2         0.056263
sexabuse3         0.029865
foodinsecure      1.000000

	 propotion of children:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       0.139519   0.025430   0.010997  0.010309    0.033677   0.042612
alcoabuse     0.025430   0.108591   0.005498  0.007560    0.026804   0.031615
drugabuse     0.010997   0.005498   0.037113  0.003436    0.010309   0.008935
prison        0.010309   0.007560   0.003436  0.032990    0.008935   0.012371
patdivorce    0.033677   0.026804   0.010309  0.008935    0.174570   0.043986
phyabuse1     0.042612   0.031615   0.008935  0.012371    0.043986   0.156701
phyabuse2     0.038488   0.025430   0.009622  0.009622    0.036426   0.049485
verbalabuse   0.021993   0.016495   0.005498  0.003436    0.025430   0.025430
sexabuse1     0.037113   0.026804   0.009622  0.008247    0.030241   0.038488
sexabuse2     0.017869   0.010997   0.003436  0.002749    0.011684   0.015120
sexabuse3     0.020619   0.013746   0.004811  0.008247    0.018557   0.019931
foodinsecure  0.018557   0.015120   0.005498  0.003436    0.029553   0.026117

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.038488     0.021993   0.037113   0.017869   0.020619
alcoabuse      0.025430     0.016495   0.026804   0.010997   0.013746
drugabuse      0.009622     0.005498   0.009622   0.003436   0.004811
prison         0.009622     0.003436   0.008247   0.002749   0.008247
patdivorce     0.036426     0.025430   0.030241   0.011684   0.018557
phyabuse1      0.049485     0.025430   0.038488   0.015120   0.019931
phyabuse2      0.145017     0.028179   0.043986   0.014433   0.016495
verbalabuse    0.028179     0.087973   0.019931   0.010309   0.006186
sexabuse1      0.043986     0.019931   0.132646   0.030241   0.030928
sexabuse2      0.014433     0.010309   0.030241   0.061856   0.014433
sexabuse3      0.016495     0.006186   0.030928   0.014433   0.065979
foodinsecure   0.015808     0.011684   0.018557   0.008247   0.010309

              foodinsecure
depress           0.018557
alcoabuse         0.015120
drugabuse         0.005498
prison            0.003436
patdivorce        0.029553
phyabuse1         0.026117
phyabuse2         0.015808
verbalabuse       0.011684
sexabuse1         0.018557
sexabuse2         0.008247
sexabuse3         0.010309
foodinsecure      0.136082

	 correlation of children:
               depress  alcoabuse  drugabuse    prison  patdivorce  phyabuse1  \
depress       1.000000   0.095352   0.088833  0.092211    0.070869   0.164733
alcoabuse     0.095352   1.000000   0.024961  0.071581    0.066445   0.129079
drugabuse     0.088833   0.024961   1.000000  0.065515    0.053378   0.045387
prison        0.092211   0.071581   0.065515  1.000000    0.046839   0.110917
patdivorce    0.070869   0.066445   0.053378  0.046839    1.000000   0.120521
phyabuse1     0.164733   0.129079   0.045387  0.110917    0.120521   1.000000
phyabuse2     0.149628   0.088377   0.063696  0.076925    0.083122   0.209062
verbalabuse   0.099031   0.078770   0.041708  0.010560    0.093674   0.113085
sexabuse1     0.158321   0.117500   0.073284  0.063904    0.055022   0.143567
sexabuse2     0.110696   0.057101   0.025050  0.016468    0.009686   0.061979
sexabuse3     0.132690   0.085206   0.050338  0.136917    0.074693   0.106294
foodinsecure -0.003614   0.003215   0.006909 -0.017193    0.044541   0.038451

              phyabuse2  verbalabuse  sexabuse1  sexabuse2  sexabuse3  \
depress        0.149628     0.099031   0.158321   0.110696   0.132690
alcoabuse      0.088377     0.078770   0.117500   0.057101   0.085206
drugabuse      0.063696     0.041708   0.073284   0.025050   0.050338
prison         0.076925     0.010560   0.063904   0.016468   0.136917
patdivorce     0.083122     0.093674   0.055022   0.009686   0.074693
phyabuse1      0.209062     0.113085   0.143567   0.061979   0.106294
phyabuse2      1.000000     0.154615   0.207227   0.064403   0.079242
verbalabuse    0.154615     1.000000   0.085994   0.071338   0.005421
sexabuse1      0.207227     0.085994   1.000000   0.269684   0.263363
sexabuse2      0.064403     0.071338   0.269684   1.000000   0.173105
sexabuse3      0.079242     0.005421   0.263363   0.173105   1.000000
foodinsecure  -0.032524    -0.002962   0.004350  -0.002059   0.015633

              foodinsecure
depress          -0.003614
alcoabuse         0.003215
drugabuse         0.006909
prison           -0.017193
patdivorce        0.044541
phyabuse1         0.038451
phyabuse2        -0.032524
verbalabuse      -0.002962
sexabuse1         0.004350
sexabuse2        -0.002059
sexabuse3         0.015633
foodinsecure      1.000000

In [27]:
np.random.choice(4,12)/10 + 0.2
for i in range(12):
    trans_rate[brfss.ace_list.values()[i]] =

SyntaxError: invalid syntax (<ipython-input-27-d0d8f2cf6006>, line 3)

In [ ]:
dict(zip(brfss.ace_list.values(), np.random.choice(4,12)/10 + 0.2))