In [1]:
from brfss import bfs_data
import brfss

from acemodel import simulate_stack, simulate_trans
from acemodel import HouseModel
from spew import *

In [2]:
import pandas as pd

In [3]:
from modelmtds import bootstrap_mtd_fill

In [4]:
spdata = pd.read_csv('spew_data/2010_ver1_45079_synth_people.txt', low_memory = False)

In [5]:
spdata['relate'].unique()

array([ 0,  1,  2, 12,  3, 10,  9,  7,  5,  6,  8,  4, 11])

In [6]:
scbrfss = bfs_data('brfss/SCBRFSS.csv')

In [7]:
data_prex = './spew_data/2010_ver1_45079_synth_'
cdl_data = cdn_data(data_prex, age = 0)
len(cdl_data)

352058

In [8]:
display(cdl_data)

,sp_id_x,sp_hh_id,age,sex,race,sporder,relate,sp_id_y,hh_income,_RACE_G1,_INCOMG
0,164099532,48930706,49,2,2,1,0,48930706,115000,2,5
1,164099533,48930706,57,1,2,2,1,48930706,115000,2,5
2,164099534,48954569,49,2,2,1,0,48954569,115000,2,5
3,164099535,48954569,57,1,2,2,1,48954569,115000,2,5
4,164099538,48964134,49,2,2,1,0,48964134,115000,2,5
...,...,...,...,...,...,...,...,...,...,...,...
352053,164066165,48841329,50,1,1,1,0,48841329,90000,1,5
352054,164066169,48822193,50,1,1,1,0,48822193,90000,1,5
352055,164066170,48815049,50,1,1,1,0,48815049,90000,1,5
352056,164066171,48811092,50,1,1,1,0,48811092,90000,1,5
352057,164066175,48812365,50,1,1,1,0,48812365,90000,1,5

In [9]:
test_model = HouseModel(cdl_data, 1,1, step_method = bootstrap_mtd_fill)

In [10]:
test_model.step()

In [11]:
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
test_model.step()
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
bst_result = simulate_stack(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel); bst_result

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bst_result_bf = bfs_data(bst_result)

In [17]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [18]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [19]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
trans_rate = {ace:0.2 for ace in brfss.ace_list.values()}

In [21]:
bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel,
                           trans_rate = trans_rate); bst_result

36.2 s Â± 71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [22]:
bst_result_bf = bfs_data(bst_result)

In [23]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [24]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [25]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
rate_list = []
for i in range(2):
    print('*' * 40, 'transmit rates:'.upper(), '*' * 40)
    al = list(brfss.ace_list.values())
    rl = np.random.choice(4,12)/10 + 0.2
    if list(rl) in rate_list:
        continue
    rate_list.append(list(rl))
    trans_rate = dict(zip(al, rl))
    
#     for t in list(brfss.ace_list.values())[0:6]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[0:6]]))    
    print(''.join(['{:>15.2}'.format(r) for r in rl[0:6]]))
#     for t in list(brfss.ace_list.values())[6:]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[6:]]))       
    print(''.join(['{:>15.2}'.format(r) for r in rl[6:]]))
    
    bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, 
                                step_num = 2, model = HouseModel, trans_rate = trans_rate)
    bst_result_bf = bfs_data(bst_result)
    print('\n\t simulation result:'.upper())
    display(bst_result)
    print('\n\t propotion:'.upper())
    display(bst_result_bf.get_prop_mat(1,1)['pr'])
    print('\n\t correlation:'.upper())
    display(bst_result_bf.get_corr_mat(1,1))
    
    print('\n\t children result:'.upper())
    display(bst_result[bst_result.age < 18])
    chd_simu_result = bfs_data(bst_result[bst_result.age < 18])
    print('\n\t propotion of children:'.upper())
    display(chd_simu_result.get_prop_mat(1,1)['pr'])
    print('\n\t correlation of children:'.upper())
    display(chd_simu_result.get_corr_mat(1,1))
    
    print('')
    
for r in rate_list:
    print(''.join([':>5.2'.format(x) for x in r]))

**************************************** TRANSMIT RATES: ****************************************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.4            0.2            0.4            0.3            0.4            0.5
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.3            0.3            0.2            0.5            0.3            0.4

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352057,163646287,60,5,5,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.191784,0.116961,0.057462,0.043198,0.084685,0.094221,0.079387,0.126498,0.062597,0.061456,0.046377,0.041976
alcoabuse,0.116961,0.295053,0.064064,0.077431,0.138153,0.156655,0.112234,0.169451,0.093569,0.081099,0.061537,0.063249
drugabuse,0.057462,0.064064,0.098215,0.040509,0.053305,0.049474,0.037982,0.065286,0.037656,0.034477,0.028446,0.023066
prison,0.043198,0.077431,0.040509,0.101801,0.055832,0.058440,0.037819,0.062271,0.044258,0.034477,0.026327,0.033010
patdivorce,0.084685,0.138153,0.053305,0.055832,0.273535,0.121607,0.092102,0.137338,0.070421,0.055832,0.048741,0.066509
phyabuse1,0.094221,0.156655,0.049474,0.058440,0.121607,0.235390,0.112968,0.153965,0.072296,0.064471,0.050534,0.056728
phyabuse2,0.079387,0.112234,0.037982,0.037819,0.092102,0.112968,0.193007,0.158448,0.072459,0.058684,0.046622,0.049148
verbalabuse,0.126498,0.169451,0.065286,0.062271,0.137338,0.153965,0.158448,0.310783,0.104980,0.085093,0.063982,0.070910
sexabuse1,0.062597,0.093569,0.037656,0.044258,0.070421,0.072296,0.072459,0.104980,0.159345,0.107181,0.080773,0.040998
sexabuse2,0.061456,0.081099,0.034477,0.034477,0.055832,0.064471,0.058684,0.085093,0.107181,0.130818,0.073274,0.031054
sexabuse3,0.046377,0.061537,0.028446,0.026327,0.048741,0.050534,0.046622,0.063982,0.080773,0.073274,0.095851,0.025674
foodinsecure,0.041976,0.063249,0.023066,0.033010,0.066509,0.056728,0.049148,0.070910,0.040998,0.031054,0.025674,0.178254

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.336248,0.329661,0.198860,0.183617,0.293829,0.272698,0.367124,0.222333,0.273936,0.241535,0.051695
alcoabuse,0.336248,1.000000,0.258498,0.343664,0.282564,0.450700,0.307166,0.368373,0.278902,0.276363,0.247698,0.061040
drugabuse,0.329661,0.258498,1.000000,0.339033,0.199299,0.208745,0.161987,0.252388,0.202032,0.215529,0.217228,0.048806
prison,0.198860,0.343664,0.339033,1.000000,0.207614,0.268752,0.152259,0.218884,0.253327,0.207520,0.186126,0.128431
patdivorce,0.183617,0.282564,0.199299,0.207614,1.000000,0.302566,0.223432,0.253637,0.164479,0.133377,0.171623,0.104041
phyabuse1,0.293829,0.450700,0.208745,0.268752,0.302566,1.000000,0.403365,0.411571,0.224046,0.235422,0.223966,0.090960
phyabuse2,0.272698,0.307166,0.161987,0.152259,0.223432,0.403365,1.000000,0.539080,0.288724,0.251248,0.242047,0.097613
verbalabuse,0.367124,0.368373,0.252388,0.218884,0.253637,0.411571,0.539080,1.000000,0.327403,0.284738,0.250967,0.087574
sexabuse1,0.222333,0.278902,0.202032,0.253327,0.164479,0.224046,0.288724,0.327403,1.000000,0.699558,0.607911,0.089906
sexabuse2,0.273936,0.276363,0.215529,0.207520,0.133377,0.235422,0.251248,0.284738,0.699558,1.000000,0.611832,0.059936
sexabuse3,0.241535,0.247698,0.217228,0.186126,0.171623,0.223966,0.242047,0.250967,0.607911,0.611832,1.000000,0.076228
foodinsecure,0.051695,0.061040,0.048806,0.128431,0.104041,0.090960,0.097613,0.087574,0.089906,0.059936,0.076228,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.107904,0.018557,0.020619,0.008247,0.026804,0.034364,0.015120,0.029553,0.010997,0.024055,0.006873,0.012371
alcoabuse,0.018557,0.096907,0.013746,0.008935,0.021306,0.032990,0.010309,0.019931,0.004811,0.011684,0.006873,0.015808
drugabuse,0.020619,0.013746,0.071478,0.010997,0.019931,0.023368,0.012371,0.018557,0.010309,0.018557,0.005498,0.010309
prison,0.008247,0.008935,0.010997,0.048797,0.017182,0.018557,0.010309,0.013058,0.006873,0.012371,0.003436,0.011684
patdivorce,0.026804,0.021306,0.019931,0.017182,0.156701,0.057045,0.021993,0.029553,0.010997,0.021993,0.006186,0.022680
phyabuse1,0.034364,0.032990,0.023368,0.018557,0.057045,0.186942,0.033677,0.050859,0.013058,0.032302,0.013746,0.029553
phyabuse2,0.015120,0.010309,0.012371,0.010309,0.021993,0.033677,0.084536,0.023368,0.008247,0.014433,0.006186,0.011684
verbalabuse,0.029553,0.019931,0.018557,0.013058,0.029553,0.050859,0.023368,0.144330,0.014433,0.030928,0.008247,0.024055
sexabuse1,0.010997,0.004811,0.010309,0.006873,0.010997,0.013058,0.008247,0.014433,0.051546,0.021306,0.007560,0.004811
sexabuse2,0.024055,0.011684,0.018557,0.012371,0.021993,0.032302,0.014433,0.030928,0.021306,0.096907,0.015120,0.012371
sexabuse3,0.006873,0.006873,0.005498,0.003436,0.006186,0.013746,0.006186,0.008247,0.007560,0.015120,0.035052,0.007560
foodinsecure,0.012371,0.015808,0.010309,0.011684,0.022680,0.029553,0.011684,0.024055,0.004811,0.012371,0.007560,0.107904

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.088251,0.161466,0.044612,0.087738,0.117334,0.069499,0.128214,0.079219,0.148155,0.054165,0.007562
alcoabuse,0.088251,1.000000,0.089474,0.065990,0.056912,0.128962,0.025725,0.057181,-0.002816,0.026199,0.063891,0.058299
drugabuse,0.161466,0.089474,1.000000,0.135284,0.093226,0.099620,0.088306,0.091019,0.116302,0.152600,0.063169,0.032486
prison,0.044612,0.065990,0.135284,1.000000,0.121754,0.112323,0.103182,0.079452,0.091474,0.119908,0.043561,0.096022
patdivorce,0.087738,0.056912,0.093226,0.121754,1.000000,0.195810,0.086487,0.054299,0.036319,0.063303,0.010365,0.051175
phyabuse1,0.117334,0.128962,0.099620,0.112323,0.195810,1.000000,0.164800,0.174281,0.039700,0.123003,0.100322,0.077560
phyabuse2,0.069499,0.025725,0.088306,0.103182,0.086487,0.164800,1.000000,0.114222,0.063240,0.075833,0.062985,0.029684
verbalabuse,0.128214,0.057181,0.091019,0.079452,0.054299,0.174281,0.114222,1.000000,0.090000,0.162956,0.049333,0.077786
sexabuse1,0.079219,-0.002816,0.116302,0.091474,0.036319,0.039700,0.063240,0.090000,1.000000,0.249356,0.141484,-0.010948
sexabuse2,0.148155,0.026199,0.152600,0.119908,0.063303,0.123003,0.075833,0.162956,0.249356,1.000000,0.215481,0.020858
sexabuse3,0.054165,0.063891,0.063169,0.043561,0.010365,0.100322,0.062985,0.049333,0.141484,0.215481,1.000000,0.066210
foodinsecure,0.007562,0.058299,0.032486,0.096022,0.051175,0.077560,0.029684,0.077786,-0.010948,0.020858,0.066210,1.000000

**************************************** TRANSMIT RATES: ****************************************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.3            0.2            0.2            0.4            0.5            0.4
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.4            0.3            0.4            0.3            0.5            0.3

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
352057,163646287,60,5,5,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.188768,0.114190,0.057706,0.039775,0.083299,0.092428,0.082158,0.122585,0.061619,0.058195,0.046540,0.039857
alcoabuse,0.114190,0.295379,0.064145,0.074171,0.134404,0.154943,0.117206,0.169125,0.087864,0.076697,0.060315,0.064716
drugabuse,0.057706,0.064145,0.096666,0.042383,0.053794,0.049393,0.039449,0.066102,0.034151,0.030646,0.027223,0.025674
prison,0.039775,0.074171,0.042383,0.100742,0.055750,0.058277,0.039857,0.059337,0.040509,0.032276,0.025348,0.028690
patdivorce,0.083299,0.134404,0.053794,0.055750,0.280870,0.120874,0.094792,0.138642,0.065123,0.051186,0.044176,0.062108
phyabuse1,0.092428,0.154943,0.049393,0.058277,0.120874,0.236042,0.117613,0.154780,0.073356,0.062189,0.050941,0.055180
phyabuse2,0.082158,0.117206,0.039449,0.039857,0.094792,0.117613,0.204092,0.164398,0.076208,0.059744,0.049882,0.044095
verbalabuse,0.122585,0.169125,0.066102,0.059337,0.138642,0.154780,0.164398,0.310213,0.102616,0.081995,0.062760,0.068058
sexabuse1,0.061619,0.087864,0.034151,0.040509,0.065123,0.073356,0.076208,0.102616,0.165132,0.105143,0.080284,0.036841
sexabuse2,0.058195,0.076697,0.030646,0.032276,0.051186,0.062189,0.059744,0.081995,0.105143,0.126987,0.071481,0.028935
sexabuse3,0.046540,0.060315,0.027223,0.025348,0.044176,0.050941,0.049882,0.062760,0.080284,0.071481,0.100090,0.025104
foodinsecure,0.039857,0.064716,0.025674,0.028690,0.062108,0.055180,0.044095,0.068058,0.036841,0.028935,0.025104,0.184612

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.327301,0.341229,0.176240,0.172171,0.288074,0.276647,0.353703,0.209548,0.262669,0.235400,0.032983
alcoabuse,0.327301,1.000000,0.264013,0.323447,0.250889,0.439899,0.309575,0.367215,0.230752,0.257987,0.224588,0.057545
drugabuse,0.341229,0.264013,1.000000,0.367034,0.200618,0.211782,0.165579,0.264199,0.165771,0.186716,0.197864,0.068284
prison,0.176240,0.323447,0.367034,1.000000,0.202963,0.269907,0.159066,0.201717,0.213617,0.194416,0.168991,0.086422
patdivorce,0.172171,0.250889,0.200618,0.202963,1.000000,0.285969,0.206854,0.247781,0.112320,0.103710,0.119099,0.058817
phyabuse1,0.288074,0.439899,0.211782,0.269907,0.285969,1.000000,0.405725,0.415188,0.218033,0.227845,0.214335,0.070429
phyabuse2,0.276647,0.309575,0.165579,0.159066,0.206854,0.405725,1.000000,0.542201,0.284044,0.252076,0.243507,0.041038
verbalabuse,0.353703,0.367215,0.264199,0.201717,0.247781,0.415188,0.542201,1.000000,0.299206,0.276603,0.228415,0.060114
sexabuse1,0.209548,0.230752,0.165771,0.213617,0.112320,0.218033,0.284044,0.299206,1.000000,0.680866,0.572138,0.044118
sexabuse2,0.262669,0.257987,0.186716,0.194416,0.103710,0.227845,0.252076,0.276603,0.680866,1.000000,0.588137,0.042510
sexabuse3,0.235400,0.224588,0.197864,0.168991,0.119099,0.214335,0.243507,0.228415,0.572138,0.588137,1.000000,0.056906
foodinsecure,0.032983,0.057545,0.068284,0.086422,0.058817,0.070429,0.041038,0.060114,0.044118,0.042510,0.056906,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.085911,0.012371,0.009622,0.010997,0.025430,0.028866,0.017182,0.019244,0.017869,0.010309,0.011684,0.009622
alcoabuse,0.012371,0.094845,0.006186,0.014433,0.026804,0.024055,0.021993,0.019931,0.017182,0.013058,0.019931,0.015120
drugabuse,0.009622,0.006186,0.035739,0.008935,0.009622,0.011684,0.006186,0.010309,0.008935,0.002062,0.006186,0.003436
prison,0.010997,0.014433,0.008935,0.069416,0.021993,0.023368,0.013746,0.014433,0.013746,0.006186,0.006186,0.014433
patdivorce,0.025430,0.026804,0.009622,0.021993,0.202749,0.047423,0.035739,0.035052,0.030241,0.015808,0.024055,0.024055
phyabuse1,0.028866,0.024055,0.011684,0.023368,0.047423,0.155326,0.032990,0.035052,0.029553,0.013058,0.022680,0.019931
phyabuse2,0.017182,0.021993,0.006186,0.013746,0.035739,0.032990,0.107216,0.024055,0.021993,0.010309,0.022680,0.015120
verbalabuse,0.019244,0.019931,0.010309,0.014433,0.035052,0.035052,0.024055,0.137457,0.025430,0.013058,0.020619,0.017869
sexabuse1,0.017869,0.017182,0.008935,0.013746,0.030241,0.029553,0.021993,0.025430,0.120275,0.026117,0.033677,0.015120
sexabuse2,0.010309,0.013058,0.002062,0.006186,0.015808,0.013058,0.010309,0.013058,0.026117,0.057732,0.017182,0.003436
sexabuse3,0.011684,0.019931,0.006186,0.006186,0.024055,0.022680,0.022680,0.020619,0.033677,0.017182,0.072165,0.010997
foodinsecure,0.009622,0.015120,0.003436,0.014433,0.024055,0.019931,0.015120,0.017869,0.015120,0.003436,0.010997,0.101031

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.051431,0.125940,0.070665,0.071106,0.152917,0.091938,0.077053,0.082678,0.081846,0.075629,0.011158
alcoabuse,0.051431,1.000000,0.051403,0.105402,0.064298,0.087845,0.130436,0.068334,0.060589,0.110960,0.172609,0.062716
drugabuse,0.125940,0.051403,1.000000,0.136787,0.031834,0.091204,0.040982,0.084428,0.076778,-0.000033,0.075079,-0.003116
prison,0.070665,0.105402,0.136787,1.000000,0.077499,0.136710,0.080158,0.055891,0.065277,0.036742,0.017884,0.096870
patdivorce,0.071106,0.064298,0.031834,0.077499,1.000000,0.109391,0.112557,0.051881,0.044770,0.043749,0.090582,0.029473
phyabuse1,0.152917,0.087845,0.091204,0.136710,0.109391,1.000000,0.145773,0.109851,0.092269,0.048426,0.122390,0.038828
phyabuse2,0.091938,0.130436,0.040982,0.080158,0.112557,0.145773,1.000000,0.087461,0.090399,0.057088,0.186655,0.045990
verbalabuse,0.077053,0.068334,0.084428,0.055891,0.051881,0.109851,0.087461,1.000000,0.079434,0.063787,0.120080,0.038373
sexabuse1,0.082678,0.060589,0.076778,0.065277,0.044770,0.092269,0.090399,0.079434,1.000000,0.252718,0.296985,0.030284
sexabuse2,0.081846,0.110960,-0.000033,0.036742,0.043749,0.048426,0.057088,0.063787,0.252718,1.000000,0.215665,-0.034091
sexabuse3,0.075629,0.172609,0.075079,0.017884,0.090582,0.122390,0.186655,0.120080,0.296985,0.215665,1.000000,0.047519
foodinsecure,0.011158,0.062716,-0.003116,0.096870,0.029473,0.038828,0.045990,0.038373,0.030284,-0.034091,0.047519,1.000000

>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2
>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2>5.2