In [1]:
from brfss import bfs_data
import brfss

from acemodel import simulate_stack, simulate_trans
from acemodel import HouseModel
from spew import *

In [2]:
import pandas as pd

In [3]:
from modelmtds import bootstrap_mtd_fill

In [4]:
spdata = pd.read_csv('spew_data/2010_ver1_45079_synth_people.txt', low_memory = False)

In [5]:
spdata['relate'].unique()

array([ 0,  1,  2, 12,  3, 10,  9,  7,  5,  6,  8,  4, 11])

In [6]:
scbrfss = bfs_data('brfss/SCBRFSS.csv')

In [7]:
data_prex = './spew_data/2010_ver1_45079_synth_'
cdl_data = cdn_data(data_prex, age = 0)
len(cdl_data)

352058

In [8]:
display(cdl_data)

,sp_id_x,sp_hh_id,age,sex,race,sporder,relate,sp_id_y,hh_income,_RACE_G1,_INCOMG
0,164099532,48930706,49,2,2,1,0,48930706,115000,2,5
1,164099533,48930706,57,1,2,2,1,48930706,115000,2,5
2,164099534,48954569,49,2,2,1,0,48954569,115000,2,5
3,164099535,48954569,57,1,2,2,1,48954569,115000,2,5
4,164099538,48964134,49,2,2,1,0,48964134,115000,2,5
...,...,...,...,...,...,...,...,...,...,...,...
352053,164066165,48841329,50,1,1,1,0,48841329,90000,1,5
352054,164066169,48822193,50,1,1,1,0,48822193,90000,1,5
352055,164066170,48815049,50,1,1,1,0,48815049,90000,1,5
352056,164066171,48811092,50,1,1,1,0,48811092,90000,1,5
352057,164066175,48812365,50,1,1,1,0,48812365,90000,1,5

In [9]:
test_model = HouseModel(cdl_data, 1,1, step_method = bootstrap_mtd_fill)

In [10]:
test_model.step()

In [11]:
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
test_model.step()
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
bst_result = simulate_stack(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel); bst_result

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bst_result_bf = bfs_data(bst_result)

In [17]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [18]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [19]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
trans_rate = {ace:0.2 for ace in brfss.ace_list.values()}

In [21]:
bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel,
                           trans_rate = trans_rate); bst_result

36.2 s Â± 71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [22]:
bst_result_bf = bfs_data(bst_result)

In [23]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [24]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [25]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
for i in range(2):
    print('*' * 20, 'transmit rates:'.upper(), '*' * 20)
    al = list(brfss.ace_list.values())
    rl = np.random.choice(4,12)/10 + 0.2
    trans_rate = dict(zip(al, rl))
    
#     for t in list(brfss.ace_list.values())[0:6]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[0:6]]))    
    print(''.join(['{:>15.2}'.format(r) for r in rl[0:6]]))
#     for t in list(brfss.ace_list.values())[6:]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[6:]]))       
    print(''.join(['{:>15.2}'.format(r) for r in rl[6:]]))
    
    bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, 
                                step_num = 2, model = HouseModel, trans_rate = trans_rate)
    bst_result_bf = bfs_data(bst_result)
    print('\n\t simulation result:'.upper())
    display(bst_result)
    print('\n\t propotion:'.upper())
    display(bst_result_bf.get_prop_mat(1,1)['pr'])
    print('\n\t correlation:'.upper())
    display(bst_result_bf.get_corr_mat(1,1))
    
    print('\n\t children result:'.upper())
    display(bst_result[bst_result.age < 18])
    chd_simu_result = bfs_data(bst_result[bst_result.age < 18])
    print('\n\t propotion of children:'.upper())
    display(chd_simu_result.get_prop_mat(1,1)['pr'])
    print('\n\t correlation of children:'.upper())
    display(chd_simu_result.get_corr_mat(1,1))
    
    print('')

TRANSMIT RATES:
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.4            0.4            0.3            0.2            0.2            0.2
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.5            0.4            0.3            0.2            0.2            0.2

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.192355,0.118510,0.058114,0.039694,0.086804,0.092754,0.081751,0.125927,0.061130,0.056565,0.045970,0.042709
alcoabuse,0.118510,0.306219,0.064960,0.073600,0.142147,0.154047,0.114924,0.172630,0.088353,0.076616,0.054691,0.070747
drugabuse,0.058114,0.064960,0.097970,0.041161,0.055913,0.052245,0.043117,0.069851,0.035618,0.032602,0.028527,0.023066
prison,0.039694,0.073600,0.041161,0.097074,0.051919,0.058929,0.037411,0.060070,0.037656,0.031380,0.021681,0.028201
patdivorce,0.086804,0.142147,0.055913,0.051919,0.271986,0.119733,0.094384,0.138235,0.062515,0.050452,0.042546,0.060152
phyabuse1,0.092754,0.154047,0.052245,0.058929,0.119733,0.223979,0.112397,0.153232,0.071399,0.061782,0.047192,0.057054
phyabuse2,0.081751,0.114924,0.043117,0.037411,0.094384,0.112397,0.201320,0.164235,0.071807,0.058358,0.047844,0.052490
verbalabuse,0.125927,0.172630,0.069851,0.060070,0.138235,0.153232,0.164235,0.316570,0.098867,0.080039,0.059418,0.069606
sexabuse1,0.061130,0.088353,0.035618,0.037656,0.062515,0.071399,0.071807,0.098867,0.154699,0.098704,0.072052,0.034966
sexabuse2,0.056565,0.076616,0.032602,0.031380,0.050452,0.061782,0.058358,0.080039,0.098704,0.118103,0.064879,0.026408
sexabuse3,0.045970,0.054691,0.028527,0.021681,0.042546,0.047192,0.047844,0.059418,0.072052,0.064879,0.089575,0.022822
foodinsecure,0.042709,0.070747,0.023066,0.028201,0.060152,0.057054,0.052490,0.069606,0.034966,0.026408,0.022822,0.173282

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.328104,0.335142,0.180141,0.196626,0.302272,0.272231,0.354726,0.220110,0.266091,0.255328,0.062860
alcoabuse,0.328104,1.000000,0.255145,0.321518,0.286976,0.444729,0.288251,0.353046,0.245871,0.271931,0.207109,0.101374
drugabuse,0.335142,0.255145,1.000000,0.359618,0.221244,0.244498,0.196247,0.280865,0.190348,0.219221,0.232661,0.054123
prison,0.180141,0.321518,0.359618,1.000000,0.193688,0.301278,0.150514,0.213055,0.211458,0.208434,0.153588,0.101557
patdivorce,0.196626,0.286976,0.221244,0.193688,1.000000,0.317024,0.222089,0.251871,0.127021,0.127639,0.143089,0.077313
phyabuse1,0.302272,0.444729,0.244498,0.301278,0.317024,1.000000,0.402606,0.424539,0.243764,0.262576,0.227866,0.115610
phyabuse2,0.272231,0.288251,0.196247,0.150514,0.222089,0.402606,1.000000,0.538849,0.280427,0.267228,0.260332,0.115996
verbalabuse,0.354726,0.353046,0.280865,0.213055,0.251871,0.424539,0.538849,1.000000,0.296631,0.284127,0.233840,0.083785
sexabuse1,0.220110,0.245871,0.190348,0.211458,0.127021,0.243764,0.280427,0.296631,1.000000,0.689208,0.563527,0.059616
sexabuse2,0.266091,0.271931,0.219221,0.208434,0.127639,0.262576,0.267228,0.284127,0.689208,1.000000,0.589175,0.048653
sexabuse3,0.255328,0.207109,0.232661,0.153588,0.143089,0.227866,0.260332,0.233840,0.563527,0.589175,1.000000,0.067538
foodinsecure,0.062860,0.101374,0.054123,0.101557,0.077313,0.115610,0.115996,0.083785,0.059616,0.048653,0.067538,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.119588,0.032990,0.011684,0.006873,0.020619,0.012371,0.027491,0.038488,0.014433,0.004811,0.006186,0.006186
alcoabuse,0.032990,0.181443,0.013058,0.015808,0.030928,0.022680,0.039863,0.057045,0.017182,0.010309,0.010309,0.011684
drugabuse,0.011684,0.013058,0.047423,0.005498,0.007560,0.008935,0.013746,0.019244,0.006873,0.003436,0.003436,0.001375
prison,0.006873,0.015808,0.005498,0.037801,0.002062,0.004811,0.009622,0.009622,0.006186,0.004124,0.002062,0.002749
patdivorce,0.020619,0.030928,0.007560,0.002062,0.103780,0.008935,0.021306,0.028179,0.010997,0.004811,0.003436,0.009622
phyabuse1,0.012371,0.022680,0.008935,0.004811,0.008935,0.068041,0.019244,0.019931,0.010997,0.002749,0.004124,0.005498
phyabuse2,0.027491,0.039863,0.013746,0.009622,0.021306,0.019244,0.137457,0.056357,0.017869,0.012371,0.011684,0.015120
verbalabuse,0.038488,0.057045,0.019244,0.009622,0.028179,0.019931,0.056357,0.197938,0.020619,0.010997,0.008935,0.008935
sexabuse1,0.014433,0.017182,0.006873,0.006186,0.010997,0.010997,0.017869,0.020619,0.075601,0.007560,0.007560,0.004124
sexabuse2,0.004811,0.010309,0.003436,0.004124,0.004811,0.002749,0.012371,0.010997,0.007560,0.033677,0.004811,0.002062
sexabuse3,0.006186,0.010309,0.003436,0.002062,0.003436,0.004124,0.011684,0.008935,0.007560,0.004811,0.029553,0.003436
foodinsecure,0.006186,0.011684,0.001375,0.002749,0.009622,0.005498,0.015120,0.008935,0.004124,0.002062,0.003436,0.056357

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.090295,0.087184,0.038013,0.082942,0.051821,0.098930,0.114606,0.062859,0.013388,0.048250,-0.007405
alcoabuse,0.090295,1.000000,0.054375,0.121756,0.102930,0.106493,0.112449,0.137606,0.034008,0.060395,0.075799,0.016407
drugabuse,0.087184,0.054375,1.000000,0.091420,0.040707,0.106649,0.098753,0.116397,0.058512,0.047973,0.056535,-0.026483
prison,0.038013,0.121756,0.091420,1.000000,-0.031998,0.046621,0.067400,0.028159,0.066005,0.082859,0.029250,0.014070
patdivorce,0.082942,0.102930,0.040707,-0.031998,1.000000,0.024394,0.067045,0.062845,0.039079,0.023920,0.007152,0.053650
phyabuse1,0.051821,0.106493,0.106649,0.046621,0.024394,1.000000,0.114075,0.064417,0.087916,0.010076,0.049545,0.028648
phyabuse2,0.098930,0.112449,0.098753,0.067400,0.067045,0.114075,1.000000,0.212465,0.082146,0.124638,0.130701,0.092859
verbalabuse,0.114606,0.137606,0.116397,0.028159,0.062845,0.064417,0.212465,1.000000,0.053679,0.060249,0.045719,-0.024167
sexabuse1,0.062859,0.034008,0.058512,0.066005,0.039079,0.087916,0.082146,0.053679,1.000000,0.105141,0.118962,-0.002247
sexabuse2,0.013388,0.060395,0.047973,0.082859,0.023920,0.010076,0.124638,0.060249,0.105141,1.000000,0.124900,0.003940
sexabuse3,0.048250,0.075799,0.056535,0.029250,0.007152,0.049545,0.130701,0.045719,0.118962,0.124900,1.000000,0.045344
foodinsecure,-0.007405,0.016407,-0.026483,0.014070,0.053650,0.028648,0.092859,-0.024167,-0.002247,0.003940,0.045344,1.000000

TRANSMIT RATES:
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.5            0.5            0.4            0.4            0.2            0.4
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.5            0.3            0.2            0.2            0.5            0.2

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
352054,163646283,60,5,5,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.193985,0.120059,0.057380,0.041894,0.082566,0.094710,0.083951,0.125194,0.063575,0.057136,0.046948,0.051186
alcoabuse,0.120059,0.305322,0.063412,0.071481,0.134485,0.155758,0.117532,0.168229,0.088027,0.076616,0.059989,0.070829
drugabuse,0.057380,0.063412,0.096503,0.040264,0.050860,0.048333,0.039041,0.063493,0.033255,0.031380,0.028527,0.026327
prison,0.041894,0.071481,0.040264,0.094303,0.049719,0.056158,0.036922,0.055913,0.040183,0.032439,0.025593,0.028120
patdivorce,0.082566,0.134485,0.050860,0.049719,0.259760,0.117206,0.090716,0.131633,0.062515,0.051023,0.043524,0.066509
phyabuse1,0.094710,0.155758,0.048333,0.056158,0.117206,0.229603,0.114027,0.150297,0.071807,0.062923,0.052245,0.059581
phyabuse2,0.083951,0.117532,0.039041,0.036922,0.090716,0.114027,0.199609,0.159426,0.073519,0.057299,0.048007,0.050371
verbalabuse,0.125194,0.168229,0.063493,0.055913,0.131633,0.150297,0.159426,0.301329,0.100171,0.081343,0.060478,0.063249
sexabuse1,0.063575,0.088027,0.033255,0.040183,0.062515,0.071807,0.073519,0.100171,0.153313,0.101231,0.074334,0.034722
sexabuse2,0.057136,0.076616,0.031380,0.032439,0.051023,0.062923,0.057299,0.081343,0.101231,0.119814,0.069036,0.029342
sexabuse3,0.046948,0.059989,0.028527,0.025593,0.043524,0.052245,0.048007,0.060478,0.074334,0.069036,0.096014,0.026408
foodinsecure,0.051186,0.070829,0.026327,0.028120,0.066509,0.059581,0.050371,0.063249,0.034722,0.029342,0.026408,0.177276

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.334039,0.331111,0.204230,0.185570,0.301682,0.286176,0.367855,0.237494,0.263951,0.243122,0.111231
alcoabuse,0.334039,1.000000,0.249631,0.317164,0.273210,0.442220,0.307400,0.360727,0.248400,0.267680,0.226069,0.094964
drugabuse,0.331111,0.249631,1.000000,0.361126,0.199196,0.210775,0.167579,0.254007,0.173512,0.206667,0.221415,0.081750
prison,0.204230,0.317164,0.361126,1.000000,0.196818,0.280731,0.154936,0.205059,0.244313,0.222753,0.192086,0.102159
patdivorce,0.185570,0.273210,0.199196,0.196818,1.000000,0.312129,0.221746,0.265205,0.143622,0.139745,0.143850,0.122173
phyabuse1,0.301682,0.442220,0.210775,0.280731,0.312129,1.000000,0.405672,0.420320,0.241575,0.259285,0.243734,0.117532
phyabuse2,0.286176,0.307400,0.167579,0.154936,0.221746,0.405672,1.000000,0.541324,0.298007,0.257183,0.244925,0.098167
verbalabuse,0.367855,0.360727,0.254007,0.205059,0.265205,0.420320,0.541324,1.000000,0.326492,0.303615,0.233365,0.056101
sexabuse1,0.237494,0.248400,0.173512,0.244313,0.143622,0.241575,0.298007,0.326492,1.000000,0.708208,0.561622,0.054819
sexabuse2,0.263951,0.267680,0.206667,0.222753,0.139745,0.259285,0.257183,0.303615,0.708208,1.000000,0.601338,0.065328
sexabuse3,0.243122,0.226069,0.221415,0.192086,0.143850,0.243734,0.244925,0.233365,0.561622,0.601338,1.000000,0.083430
foodinsecure,0.111231,0.094964,0.081750,0.102159,0.122173,0.117532,0.098167,0.056101,0.054819,0.065328,0.083430,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.141581,0.058419,0.015808,0.019931,0.021306,0.041237,0.041924,0.044674,0.015808,0.010309,0.023368,0.012371
alcoabuse,0.058419,0.214433,0.029553,0.026804,0.032302,0.059107,0.057732,0.048110,0.020619,0.013746,0.031615,0.019931
drugabuse,0.015808,0.029553,0.063918,0.012371,0.012371,0.019244,0.016495,0.016495,0.008247,0.005498,0.013058,0.006873
prison,0.019931,0.026804,0.012371,0.057045,0.013746,0.019931,0.014433,0.015808,0.005498,0.004124,0.009622,0.004811
patdivorce,0.021306,0.032302,0.012371,0.013746,0.081100,0.019931,0.018557,0.018557,0.006186,0.007560,0.008935,0.008247
phyabuse1,0.041237,0.059107,0.019244,0.019931,0.019931,0.138832,0.037801,0.035739,0.016495,0.010309,0.026117,0.012371
phyabuse2,0.041924,0.057732,0.016495,0.014433,0.018557,0.037801,0.133333,0.041924,0.016495,0.008935,0.027491,0.011684
verbalabuse,0.044674,0.048110,0.016495,0.015808,0.018557,0.035739,0.041924,0.136082,0.013746,0.011684,0.017869,0.010309
sexabuse1,0.015808,0.020619,0.008247,0.005498,0.006186,0.016495,0.016495,0.013746,0.050859,0.008935,0.015808,0.002749
sexabuse2,0.010309,0.013746,0.005498,0.004124,0.007560,0.010309,0.008935,0.011684,0.008935,0.040550,0.010997,0.004811
sexabuse3,0.023368,0.031615,0.013058,0.009622,0.008935,0.026117,0.027491,0.017869,0.015808,0.010997,0.079725,0.006873
foodinsecure,0.012371,0.019931,0.006873,0.004811,0.008247,0.012371,0.011684,0.010309,0.002749,0.004811,0.006873,0.068041

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.196107,0.079251,0.146619,0.103224,0.179034,0.194476,0.212551,0.112369,0.066434,0.127928,0.031186
alcoabuse,0.196107,1.000000,0.157852,0.153082,0.133093,0.206720,0.208867,0.134512,0.107709,0.062386,0.130604,0.051677
drugabuse,0.079251,0.157852,1.000000,0.153796,0.107638,0.122612,0.095881,0.092963,0.092974,0.060240,0.120180,0.040974
prison,0.146619,0.153082,0.153796,1.000000,0.144035,0.149783,0.086593,0.101163,0.050965,0.039578,0.080770,0.015917
patdivorce,0.103224,0.133093,0.107638,0.144035,1.000000,0.091874,0.083444,0.080346,0.034361,0.079330,0.033391,0.039703
phyabuse1,0.179034,0.206720,0.122612,0.149783,0.091874,1.000000,0.164113,0.142095,0.124182,0.068615,0.160675,0.033592
phyabuse2,0.194476,0.208867,0.095881,0.086593,0.083444,0.164113,1.000000,0.204024,0.130058,0.052618,0.183123,0.030510
verbalabuse,0.212551,0.134512,0.092963,0.101163,0.080346,0.142095,0.204024,1.000000,0.090593,0.091168,0.075589,0.012162
sexabuse1,0.112369,0.107709,0.092974,0.050965,0.034361,0.124182,0.130058,0.090593,1.000000,0.158581,0.197486,-0.012858
sexabuse2,0.066434,0.062386,0.060240,0.039578,0.079330,0.068615,0.052618,0.091168,0.158581,1.000000,0.145314,0.041312
sexabuse3,0.127928,0.130604,0.120180,0.080770,0.033391,0.160675,0.183123,0.075589,0.197486,0.145314,1.000000,0.021233
foodinsecure,0.031186,0.051677,0.040974,0.015917,0.039703,0.033592,0.030510,0.012162,-0.012858,0.041312,0.021233,1.000000