In [1]:
from brfss import bfs_data
import brfss

from acemodel import simulate_stack, simulate_trans
from acemodel import HouseModel
from spew import *

In [2]:
import pandas as pd

In [3]:
from modelmtds import bootstrap_mtd_fill

In [4]:
spdata = pd.read_csv('spew_data/2010_ver1_45079_synth_people.txt', low_memory = False)

In [5]:
spdata['relate'].unique()

array([ 0,  1,  2, 12,  3, 10,  9,  7,  5,  6,  8,  4, 11])

In [6]:
scbrfss = bfs_data('brfss/SCBRFSS.csv')

In [7]:
data_prex = './spew_data/2010_ver1_45079_synth_'
cdl_data = cdn_data(data_prex, age = 0)
len(cdl_data)

352058

In [8]:
display(cdl_data)

,sp_id_x,sp_hh_id,age,sex,race,sporder,relate,sp_id_y,hh_income,_RACE_G1,_INCOMG
0,164099532,48930706,49,2,2,1,0,48930706,115000,2,5
1,164099533,48930706,57,1,2,2,1,48930706,115000,2,5
2,164099534,48954569,49,2,2,1,0,48954569,115000,2,5
3,164099535,48954569,57,1,2,2,1,48954569,115000,2,5
4,164099538,48964134,49,2,2,1,0,48964134,115000,2,5
...,...,...,...,...,...,...,...,...,...,...,...
352053,164066165,48841329,50,1,1,1,0,48841329,90000,1,5
352054,164066169,48822193,50,1,1,1,0,48822193,90000,1,5
352055,164066170,48815049,50,1,1,1,0,48815049,90000,1,5
352056,164066171,48811092,50,1,1,1,0,48811092,90000,1,5
352057,164066175,48812365,50,1,1,1,0,48812365,90000,1,5

In [9]:
test_model = HouseModel(cdl_data, 1,1, step_method = bootstrap_mtd_fill)

In [10]:
test_model.step()

In [11]:
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
test_model.step()
res = test_model.datacollector.model_vars['Output'][-1]
result_df = pd.DataFrame(res); result_df

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,165641324,50,1,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12264,162963346,72,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0
12265,162963347,72,1,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12266,162963348,72,1,1,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
12267,162963349,72,1,1,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12268,162963350,72,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
result_df[result_df['age'] < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12109,150844527,15,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12111,151485100,9,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12113,151485102,4,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12115,151485214,9,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12117,151485216,4,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
bst_result = simulate_stack(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel); bst_result

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,165121904,85,1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,165641323,29,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352057,163646287,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
bst_result_bf = bfs_data(bst_result)

In [17]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [18]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [19]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
trans_rate = {ace:0.2 for ace in brfss.ace_list.values()}

In [21]:
bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, step_num = 2, model = HouseModel,
                           trans_rate = trans_rate); bst_result

36.2 s Â± 71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [22]:
bst_result_bf = bfs_data(bst_result)

In [23]:
bst_result_bf.get_prop_mat(1,1)['pr']

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.190154,0.121689,0.056728,0.040916,0.087456,0.093732,0.081180,0.127313,0.066183,0.060559,0.048333,0.042220
alcoabuse,0.121689,0.306137,0.064227,0.073111,0.144429,0.157144,0.118592,0.175564,0.095688,0.081506,0.061374,0.064145
drugabuse,0.056728,0.064227,0.096992,0.040101,0.056158,0.051430,0.040427,0.069199,0.036596,0.033010,0.028446,0.018502
prison,0.040916,0.073111,0.040101,0.096829,0.053142,0.057543,0.039449,0.062678,0.042139,0.033825,0.026164,0.025267
patdivorce,0.087456,0.144429,0.056158,0.053142,0.271416,0.120385,0.094303,0.140843,0.068384,0.054446,0.046051,0.063982
phyabuse1,0.093732,0.157144,0.051430,0.057543,0.120385,0.224061,0.117532,0.155025,0.074497,0.065205,0.051430,0.048089
phyabuse2,0.081180,0.118592,0.040427,0.039449,0.094303,0.117532,0.200098,0.165213,0.077512,0.060804,0.050778,0.046785
verbalabuse,0.127313,0.175564,0.069199,0.062678,0.140843,0.155025,0.165213,0.312984,0.107262,0.086234,0.065694,0.069932
sexabuse1,0.066183,0.095688,0.036596,0.042139,0.068384,0.074497,0.077512,0.107262,0.162442,0.108403,0.078980,0.039694
sexabuse2,0.060559,0.081506,0.033010,0.033825,0.054446,0.065205,0.060804,0.086234,0.108403,0.127476,0.072622,0.033092
sexabuse3,0.048333,0.061374,0.028446,0.026164,0.046051,0.051430,0.050778,0.065694,0.078980,0.072622,0.096422,0.023555
foodinsecure,0.042220,0.064145,0.018502,0.025267,0.063982,0.048089,0.046785,0.069932,0.039694,0.033092,0.023555,0.190562

In [24]:
bst_result_bf.get_corr_mat(1,1)

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.350960,0.329654,0.193914,0.205410,0.312458,0.274722,0.372577,0.243832,0.277510,0.258982,0.038828
alcoabuse,0.350960,1.000000,0.253184,0.318923,0.299282,0.460787,0.310942,0.373149,0.270344,0.276375,0.234166,0.032083
drugabuse,0.329654,0.253184,1.000000,0.350887,0.226682,0.240669,0.177525,0.283035,0.190915,0.209178,0.218575,0.000162
prison,0.193914,0.318923,0.350887,1.000000,0.204257,0.290721,0.169667,0.236069,0.242112,0.217810,0.192774,0.058677
patdivorce,0.205410,0.299282,0.226682,0.204257,1.000000,0.321279,0.224795,0.271059,0.148113,0.133826,0.151461,0.070203
phyabuse1,0.312458,0.460787,0.240669,0.290721,0.321279,1.000000,0.435799,0.439090,0.247725,0.263505,0.242342,0.032922
phyabuse2,0.274722,0.310942,0.177525,0.169667,0.224795,0.435799,1.000000,0.552972,0.304997,0.264535,0.266617,0.055074
verbalabuse,0.372577,0.373149,0.283035,0.236069,0.271059,0.439090,0.552972,1.000000,0.329865,0.299619,0.259480,0.056500
sexabuse1,0.243832,0.270344,0.190915,0.242112,0.148113,0.247725,0.304997,0.329865,1.000000,0.712886,0.581554,0.060320
sexabuse2,0.277510,0.276375,0.209178,0.217810,0.133826,0.263505,0.264535,0.299619,0.712886,1.000000,0.612865,0.067181
sexabuse3,0.258982,0.234166,0.218575,0.192774,0.151461,0.242342,0.266617,0.259480,0.581554,0.612865,1.000000,0.044692
foodinsecure,0.038828,0.032083,0.000162,0.058677,0.070203,0.032922,0.055074,0.056500,0.060320,0.067181,0.044692,1.000000

In [25]:
bst_result[bst_result.age < 18]

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
rate_list = []
for i in range(2):
    print('*' * 40, 'transmit rates:'.upper(), '*' * 40)
    al = list(brfss.ace_list.values())
    rl = np.random.choice(4,12)/10 + 0.2
    if rl in rate_list:
        continue
    rate_list.append(rl)
    trans_rate = dict(zip(al, rl))
    
#     for t in list(brfss.ace_list.values())[0:6]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[0:6]]))    
    print(''.join(['{:>15.2}'.format(r) for r in rl[0:6]]))
#     for t in list(brfss.ace_list.values())[6:]:
#         print('{:>15}'.format(t), end='')
    print(''.join(['{:>15}'.format(t) for t in al[6:]]))       
    print(''.join(['{:>15.2}'.format(r) for r in rl[6:]]))
    
    bst_result = simulate_trans(bootstrap_mtd_fill, cdl_data = cdl_data, 
                                step_num = 2, model = HouseModel, trans_rate = trans_rate)
    bst_result_bf = bfs_data(bst_result)
    print('\n\t simulation result:'.upper())
    display(bst_result)
    print('\n\t propotion:'.upper())
    display(bst_result_bf.get_prop_mat(1,1)['pr'])
    print('\n\t correlation:'.upper())
    display(bst_result_bf.get_corr_mat(1,1))
    
    print('\n\t children result:'.upper())
    display(bst_result[bst_result.age < 18])
    chd_simu_result = bfs_data(bst_result[bst_result.age < 18])
    print('\n\t propotion of children:'.upper())
    display(chd_simu_result.get_prop_mat(1,1)['pr'])
    print('\n\t correlation of children:'.upper())
    display(chd_simu_result.get_corr_mat(1,1))
    
    print('')
    
print(rate_list)

******************** TRANSMIT RATES: ********************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.3            0.2            0.5            0.4            0.2            0.4
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.5            0.2            0.4            0.3            0.4            0.5

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,165121905,85,1,1,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
3,165641324,50,1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
352056,163646286,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
352057,163646287,60,5,5,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.187872,0.116554,0.056891,0.040183,0.081995,0.091776,0.083299,0.122993,0.062515,0.055913,0.044910,0.042791
alcoabuse,0.116554,0.301003,0.063412,0.073030,0.135382,0.154373,0.114272,0.170430,0.091287,0.076779,0.059092,0.066020
drugabuse,0.056891,0.063412,0.103024,0.043687,0.055424,0.049800,0.040346,0.066020,0.037004,0.030320,0.027223,0.018013
prison,0.040183,0.073030,0.043687,0.099845,0.050615,0.056076,0.037737,0.059174,0.041487,0.032195,0.025185,0.029424
patdivorce,0.081995,0.135382,0.055424,0.050615,0.262532,0.114924,0.090716,0.130573,0.064879,0.048822,0.044828,0.058848
phyabuse1,0.091776,0.154373,0.049800,0.056076,0.114924,0.230907,0.117613,0.152661,0.072867,0.059255,0.046703,0.052979
phyabuse2,0.083299,0.114272,0.040346,0.037737,0.090716,0.117613,0.204092,0.160404,0.074986,0.058032,0.046133,0.052653
verbalabuse,0.122993,0.170430,0.066020,0.059174,0.130573,0.152661,0.160404,0.306708,0.102046,0.078001,0.059663,0.063493
sexabuse1,0.062515,0.091287,0.037004,0.041487,0.064879,0.072867,0.074986,0.102046,0.161790,0.102779,0.077838,0.035781
sexabuse2,0.055913,0.076779,0.030320,0.032195,0.048822,0.059255,0.058032,0.078001,0.102779,0.121444,0.067813,0.027468
sexabuse3,0.044910,0.059092,0.027223,0.025185,0.044828,0.046703,0.046133,0.059663,0.077838,0.067813,0.096014,0.025593
foodinsecure,0.042791,0.066020,0.018013,0.029424,0.058848,0.052979,0.052653,0.063493,0.035781,0.027468,0.025593,0.183063

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.334899,0.316116,0.182955,0.190100,0.294002,0.285564,0.362929,0.223292,0.259404,0.233507,0.055598
alcoabuse,0.334899,1.000000,0.232371,0.312522,0.279241,0.439055,0.285820,0.369285,0.252122,0.268465,0.223415,0.061548
drugabuse,0.316116,0.232371,1.000000,0.366502,0.212152,0.203047,0.157684,0.245558,0.181654,0.179349,0.193519,-0.007205
prison,0.182955,0.312522,0.366502,1.000000,0.184993,0.261375,0.143674,0.206522,0.229461,0.204945,0.176613,0.096138
patdivorce,0.190100,0.279241,0.212152,0.184993,1.000000,0.292857,0.209405,0.246685,0.138265,0.117858,0.151364,0.063397
phyabuse1,0.294002,0.439055,0.203047,0.261375,0.292857,1.000000,0.415010,0.421151,0.228806,0.226751,0.197600,0.065709
phyabuse2,0.285564,0.285820,0.157684,0.143674,0.209405,0.415010,1.000000,0.526270,0.282748,0.252540,0.223489,0.098109
verbalabuse,0.362929,0.369285,0.245558,0.206522,0.246685,0.421151,0.526270,1.000000,0.308712,0.270565,0.222404,0.041197
sexabuse1,0.223292,0.252122,0.181654,0.229461,0.138265,0.228806,0.282748,0.308712,1.000000,0.691094,0.574271,0.043279
sexabuse2,0.259404,0.268465,0.179349,0.204945,0.117858,0.226751,0.252540,0.270565,0.691094,1.000000,0.583511,0.041448
sexabuse3,0.233507,0.223415,0.193519,0.176613,0.151364,0.197600,0.223489,0.222404,0.574271,0.583511,1.000000,0.070361
foodinsecure,0.055598,0.061548,-0.007205,0.096138,0.063397,0.065709,0.098109,0.041197,0.043279,0.041448,0.070361,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
49,165829045,2,1,1,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
52,165829052,8,1,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.076289,0.019244,0.010309,0.010997,0.008935,0.017182,0.021306,0.010997,0.013058,0.008935,0.007560,0.014433
alcoabuse,0.019244,0.094845,0.011684,0.009622,0.015808,0.026117,0.026117,0.013746,0.016495,0.013058,0.011684,0.019244
drugabuse,0.010309,0.011684,0.083849,0.016495,0.013058,0.019931,0.020619,0.013746,0.017869,0.011684,0.009622,0.010997
prison,0.010997,0.009622,0.016495,0.068729,0.005498,0.019931,0.019244,0.010997,0.017182,0.006186,0.006186,0.013058
patdivorce,0.008935,0.015808,0.013058,0.005498,0.091409,0.021306,0.027491,0.006873,0.011684,0.010997,0.009622,0.013058
phyabuse1,0.017182,0.026117,0.019931,0.019931,0.021306,0.135395,0.050172,0.025430,0.032302,0.015120,0.016495,0.026117
phyabuse2,0.021306,0.026117,0.020619,0.019244,0.027491,0.050172,0.160137,0.032990,0.029553,0.020619,0.016495,0.034364
verbalabuse,0.010997,0.013746,0.013746,0.010997,0.006873,0.025430,0.032990,0.096220,0.018557,0.013058,0.012371,0.019244
sexabuse1,0.013058,0.016495,0.017869,0.017182,0.011684,0.032302,0.029553,0.018557,0.097595,0.023368,0.024055,0.023368
sexabuse2,0.008935,0.013058,0.011684,0.006186,0.010997,0.015120,0.020619,0.013058,0.023368,0.063230,0.017182,0.008935
sexabuse3,0.007560,0.011684,0.009622,0.006186,0.009622,0.016495,0.016495,0.012371,0.024055,0.017182,0.063918,0.013746
foodinsecure,0.014433,0.019244,0.010997,0.013058,0.013058,0.026117,0.034364,0.019244,0.023368,0.008935,0.013746,0.136082

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.154389,0.053178,0.085668,0.025636,0.075452,0.093363,0.046704,0.071251,0.063631,0.041334,0.044512
alcoabuse,0.154389,1.000000,0.045946,0.041866,0.084532,0.132423,0.101705,0.053466,0.083246,0.099023,0.078437,0.063080
drugabuse,0.053178,0.045946,1.000000,0.153054,0.067529,0.090463,0.070749,0.069468,0.117763,0.094613,0.062874,-0.004354
prison,0.085668,0.041866,0.153054,1.000000,-0.010755,0.122756,0.088790,0.058756,0.139514,0.029881,0.028968,0.042719
patdivorce,0.025636,0.084532,0.067529,-0.010755,1.000000,0.090560,0.121616,-0.022622,0.032305,0.074378,0.053613,0.006267
phyabuse1,0.075452,0.132423,0.090463,0.122756,0.090560,1.000000,0.227055,0.122917,0.187996,0.078770,0.093687,0.065567
phyabuse2,0.093363,0.101705,0.070749,0.088790,0.121616,0.227055,1.000000,0.162568,0.127945,0.117563,0.069776,0.099984
verbalabuse,0.046704,0.053466,0.069468,0.058756,-0.022622,0.122917,0.162568,1.000000,0.104739,0.097177,0.086244,0.060825
sexabuse1,0.071251,0.083246,0.117763,0.139514,0.032305,0.187996,0.127945,0.104739,1.000000,0.238097,0.245445,0.099129
sexabuse2,0.063631,0.099023,0.094613,0.029881,0.074378,0.078770,0.117563,0.097177,0.238097,1.000000,0.220734,0.003957
sexabuse3,0.041334,0.078437,0.062874,0.028968,0.053613,0.093687,0.069776,0.086244,0.245445,0.220734,1.000000,0.060185
foodinsecure,0.044512,0.063080,-0.004354,0.042719,0.006267,0.065567,0.099984,0.060825,0.099129,0.003957,0.060185,1.000000

******************** TRANSMIT RATES: ********************
        depress      alcoabuse      drugabuse         prison     patdivorce      phyabuse1
            0.4            0.4            0.2            0.2            0.4            0.4
      phyabuse2    verbalabuse      sexabuse1      sexabuse2      sexabuse3   foodinsecure
            0.4            0.5            0.4            0.5            0.5            0.4

	 SIMULATION RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
0,165121903,85,1,1,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,165121904,85,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,165121905,85,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,165641324,50,1,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,165641323,29,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352053,163646280,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
352054,163646283,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
352055,163646284,60,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352056,163646286,60,5,5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352057,163646287,60,5,5,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0

	 PROPOTION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.187709,0.112968,0.057462,0.040672,0.083381,0.091450,0.080936,0.124868,0.065531,0.061945,0.049800,0.049311
alcoabuse,0.112968,0.303529,0.061700,0.074904,0.138398,0.152824,0.111745,0.166436,0.092021,0.078980,0.059663,0.065939
drugabuse,0.057462,0.061700,0.096014,0.042220,0.052735,0.046459,0.038960,0.066428,0.037085,0.034233,0.030565,0.024533
prison,0.040672,0.074904,0.042220,0.099845,0.054365,0.057869,0.038878,0.061293,0.042709,0.035292,0.026653,0.031217
patdivorce,0.083381,0.138398,0.052735,0.054365,0.276551,0.115902,0.090390,0.134485,0.067243,0.052816,0.045970,0.053876
phyabuse1,0.091450,0.152824,0.046459,0.057869,0.115902,0.229033,0.115657,0.155921,0.073437,0.062841,0.049556,0.053631
phyabuse2,0.080936,0.111745,0.038960,0.038878,0.090390,0.115657,0.202217,0.166843,0.077675,0.060885,0.051104,0.046948
verbalabuse,0.124868,0.166436,0.066428,0.061293,0.134485,0.155921,0.166843,0.315103,0.105632,0.084848,0.066183,0.070584
sexabuse1,0.065531,0.092021,0.037085,0.042709,0.067243,0.073437,0.077675,0.105632,0.164480,0.107996,0.084766,0.039531
sexabuse2,0.061945,0.078980,0.034233,0.035292,0.052816,0.062841,0.060885,0.084848,0.107996,0.131388,0.076616,0.028120
sexabuse3,0.049800,0.059663,0.030565,0.026653,0.045970,0.049556,0.051104,0.066183,0.084766,0.076616,0.102616,0.024044
foodinsecure,0.049311,0.065939,0.024533,0.031217,0.053876,0.053631,0.046948,0.070584,0.039531,0.028120,0.024044,0.178254

	 CORRELATION:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.311875,0.342831,0.187333,0.180179,0.295329,0.274028,0.362293,0.239417,0.282625,0.257721,0.106067
alcoabuse,0.311875,1.000000,0.240350,0.323552,0.264792,0.431180,0.272733,0.331435,0.246977,0.251726,0.204377,0.067245
drugabuse,0.342831,0.240350,1.000000,0.369483,0.198682,0.197645,0.165165,0.264301,0.194963,0.217203,0.231675,0.065792
prison,0.187333,0.323552,0.369483,1.000000,0.199503,0.277843,0.155200,0.214195,0.236527,0.218940,0.180345,0.116953
patdivorce,0.180179,0.264792,0.198682,0.199503,1.000000,0.279653,0.191851,0.227839,0.131204,0.109066,0.129598,0.026750
phyabuse1,0.295329,0.431180,0.197645,0.277843,0.279653,1.000000,0.410852,0.429035,0.229598,0.230697,0.204314,0.079621
phyabuse2,0.274028,0.272733,0.165165,0.155200,0.191851,0.410852,1.000000,0.552675,0.298293,0.252905,0.249036,0.070917
verbalabuse,0.362293,0.331435,0.264301,0.214195,0.227839,0.429035,0.552675,1.000000,0.312422,0.276842,0.240105,0.081080
sexabuse1,0.239417,0.246977,0.194963,0.236527,0.131204,0.229598,0.298293,0.312422,1.000000,0.689785,0.603479,0.071971
sexabuse2,0.282625,0.251726,0.217203,0.218940,0.109066,0.230697,0.252905,0.276842,0.689785,1.000000,0.615843,0.036345
sexabuse3,0.257721,0.204377,0.231675,0.180345,0.129598,0.204314,0.249036,0.240105,0.603479,0.615843,1.000000,0.049531
foodinsecure,0.106067,0.067245,0.065792,0.116953,0.026750,0.079621,0.070917,0.081080,0.071971,0.036345,0.049531,1.000000

	 CHILDREN RESULT:

,id,age,_RACE_G1,_INCOMG,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
48,165829048,8,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
49,165829045,2,1,1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
52,165829052,8,1,1,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
53,165829049,2,1,1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
58,165829056,8,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352021,141520733,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352022,141520751,17,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352048,159390840,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352049,159390843,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
352050,159390873,2,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

	 PROPOTION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,0.105842,0.028179,0.004124,0.004124,0.025430,0.021306,0.022680,0.041924,0.027491,0.030928,0.019931,0.011684
alcoabuse,0.028179,0.175258,0.006873,0.006186,0.041237,0.029553,0.036426,0.055670,0.035739,0.030928,0.024742,0.019244
drugabuse,0.004124,0.006873,0.027491,0.001375,0.007560,0.005498,0.004124,0.013058,0.006186,0.007560,0.005498,0.003436
prison,0.004124,0.006186,0.001375,0.025430,0.007560,0.007560,0.006186,0.008247,0.007560,0.005498,0.004811,0.004811
patdivorce,0.025430,0.041237,0.007560,0.007560,0.164261,0.029553,0.028179,0.045361,0.025430,0.024055,0.019931,0.018557
phyabuse1,0.021306,0.029553,0.005498,0.007560,0.029553,0.115464,0.036426,0.051546,0.021993,0.021993,0.015120,0.016495
phyabuse2,0.022680,0.036426,0.004124,0.006186,0.028179,0.036426,0.127835,0.063230,0.027491,0.024055,0.021306,0.021993
verbalabuse,0.041924,0.055670,0.013058,0.008247,0.045361,0.051546,0.063230,0.220619,0.041924,0.041924,0.032302,0.028866
sexabuse1,0.027491,0.035739,0.006186,0.007560,0.025430,0.021993,0.027491,0.041924,0.103780,0.037113,0.042612,0.020619
sexabuse2,0.030928,0.030928,0.007560,0.005498,0.024055,0.021993,0.024055,0.041924,0.037113,0.105842,0.035739,0.009622
sexabuse3,0.019931,0.024742,0.005498,0.004811,0.019931,0.015120,0.021306,0.032302,0.042612,0.035739,0.077663,0.008935
foodinsecure,0.011684,0.019244,0.003436,0.004811,0.018557,0.016495,0.021993,0.028866,0.020619,0.009622,0.008935,0.103780

	 CORRELATION OF CHILDREN:

,depress,alcoabuse,drugabuse,prison,patdivorce,phyabuse1,phyabuse2,verbalabuse,sexabuse1,sexabuse2,sexabuse3,foodinsecure
depress,1.000000,0.082329,0.024134,0.029573,0.070571,0.092407,0.089077,0.145602,0.175943,0.208426,0.142238,0.007456
alcoabuse,0.082329,1.000000,0.033054,0.028886,0.088376,0.076685,0.110456,0.107866,0.151366,0.105834,0.109393,0.009105
drugabuse,0.024134,0.033054,1.000000,0.026242,0.050251,0.044475,0.011161,0.103143,0.066828,0.092450,0.076852,0.011699
prison,0.029573,0.028886,0.026242,1.000000,0.058000,0.091908,0.055831,0.040399,0.102499,0.057956,0.067311,0.045238
patdivorce,0.070571,0.088376,0.050251,0.058000,1.000000,0.089411,0.058039,0.059372,0.074184,0.058511,0.072347,0.013360
phyabuse1,0.092407,0.076685,0.044475,0.091908,0.089411,1.000000,0.203034,0.196749,0.102707,0.099398,0.071937,0.046294
phyabuse2,0.089077,0.110456,0.011161,0.055831,0.058039,0.203034,1.000000,0.252981,0.139686,0.102459,0.127315,0.085693
verbalabuse,0.145602,0.107866,0.103143,0.040399,0.059372,0.196749,0.252981,1.000000,0.150469,0.145602,0.136676,0.047209
sexabuse1,0.175943,0.151366,0.066828,0.102499,0.074184,0.102707,0.139686,0.150469,1.000000,0.278500,0.423305,0.105884
sexabuse2,0.208426,0.105834,0.092450,0.057956,0.058511,0.099398,0.102459,0.145602,0.278500,1.000000,0.334227,-0.014520
sexabuse3,0.142238,0.109393,0.076852,0.067311,0.072347,0.071937,0.127315,0.136676,0.423305,0.334227,1.000000,0.010718
foodinsecure,0.007456,0.009105,0.011699,0.045238,0.013360,0.046294,0.085693,0.047209,0.105884,-0.014520,0.010718,1.000000